// frontend/src/components/chat/header/EditableConversationTitle.tsx
import { useEffect, useRef, useState, type KeyboardEvent } from "react";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

type EditableConversationTitleProps = {
  title: string;
  disabled?: boolean;
  onCommit: (nextTitle: string) => Promise<void>;
  startEditingSignal?: number;
};

export function EditableConversationTitle({
  title,
  disabled = false,
  onCommit,
  startEditingSignal = 0,
}: EditableConversationTitleProps) {
  const [editing, setEditing] = useState(false);
  const [value, setValue] = useState(title);
  const [busy, setBusy] = useState(false);
  const inputRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    if (!editing) setValue(title);
  }, [title, editing]);

  useEffect(() => {
    if (disabled) return;
    if (startEditingSignal <= 0) return;
    setEditing(true);
  }, [disabled, startEditingSignal]);

  useEffect(() => {
    if (!editing) return;
    const id = window.setTimeout(() => {
      inputRef.current?.focus();
      inputRef.current?.select();
    }, 0);
    return () => window.clearTimeout(id);
  }, [editing]);

  async function commit() {
    const next = value.trim();
    if (!next || next === title.trim()) {
      setEditing(false);
      setValue(title);
      return;
    }
    setBusy(true);
    try {
      await onCommit(next);
      setEditing(false);
    } finally {
      setBusy(false);
    }
  }

  function onKeyDown(e: KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Enter") {
      e.preventDefault();
      void commit();
      return;
    }
    if (e.key === "Escape") {
      e.preventDefault();
      setEditing(false);
      setValue(title);
    }
  }

  if (editing && !disabled) {
    return (
      <Input
        ref={inputRef}
        value={value}
        maxLength={120}
        disabled={busy}
        onChange={(e) => setValue(e.target.value)}
        onBlur={() => void commit()}
        onKeyDown={onKeyDown}
        className="h-7 max-w-[460px] text-sm font-medium"
        aria-label="Conversation title"
      />
    );
  }

  return (
    <button
      type="button"
      className={cn(
        "truncate rounded-md px-1 py-0.5 text-left text-sm font-medium text-foreground",
        "hover:bg-muted/60",
        disabled && "cursor-default hover:bg-transparent",
      )}
      disabled={disabled}
      onClick={() => setEditing(true)}
      title={disabled ? title : "Click to rename conversation"}
      aria-label={disabled ? "Conversation title" : "Edit conversation title"}
    >
      {title}
    </button>
  );
}

// frontend/src/components/chat/header/EditableConversationTitle.svelte
<script lang="ts">
  let {
    title,
    disabled = false,
    onCommit,
  }: {
    title: string;
    disabled?: boolean;
    onCommit: (nextTitle: string) => Promise<void>;
  } = $props();

  let editing = $state(false);
  let value = $state("");
  let busy = $state(false);
  let inputEl = $state<HTMLInputElement | null>(null);

  $effect(() => {
    if (!editing) value = title;
  });

  $effect(() => {
    if (!editing || !inputEl) return;
    const id = window.setTimeout(() => {
      inputEl?.focus();
      inputEl?.select();
    }, 0);
    return () => window.clearTimeout(id);
  });

  async function commit(): Promise<void> {
    const next = value.trim();
    if (!next || next === title.trim()) {
      editing = false;
      value = title;
      return;
    }
    busy = true;
    try {
      await onCommit(next);
      editing = false;
    } finally {
      busy = false;
    }
  }
</script>

{#if editing && !disabled}
  <input
    bind:this={inputEl}
    data-testid="conversation-title"
    class="h-7 max-w-[460px] rounded-md border border-input bg-background px-2 text-sm font-medium"
    maxlength={120}
    {value}
    disabled={busy}
    aria-label="Conversation title"
    oninput={(e) => (value = e.currentTarget.value)}
    onblur={() => void commit()}
    onkeydown={(e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        void commit();
      }
      if (e.key === "Escape") {
        e.preventDefault();
        editing = false;
        value = title;
      }
    }}
  />
{:else}
  <button
    type="button"
    data-testid="conversation-title"
    class="min-w-[10ch] truncate rounded-md px-1 py-0.5 text-left text-sm font-medium text-foreground hover:bg-muted/60 disabled:cursor-default disabled:hover:bg-transparent"
    {disabled}
    title={disabled ? title : "Click to rename conversation"}
    onclick={() => {
      if (!disabled) editing = true;
    }}
  >
    {title}
  </button>
{/if}
