// frontend/src/components/ThemeToggle.tsx
import { Moon, Sun } from "lucide-react";
import { useEffect, useState } from "react";

import { Button } from "@/components/ui/button";

export function ThemeToggle() {
  const [dark, setDark] = useState(() => {
    if (typeof window === "undefined") return true;
    return localStorage.getItem("theme") !== "light";
  });

  useEffect(() => {
    document.documentElement.classList.toggle("dark", dark);
    localStorage.setItem("theme", dark ? "dark" : "light");
  }, [dark]);

  return (
    <Button
      type="button"
      variant="ghost"
      size="icon"
      className="h-8 w-8 text-muted-foreground"
      title={dark ? "Switch to light mode" : "Switch to dark mode"}
      onClick={() => setDark((d) => !d)}
    >
      {dark ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
    </Button>
  );
}

// frontend3/src/components/ThemeToggle.svelte
<script lang="ts">
  import Icon from "@/components/ui/Icon.svelte";

  let dark = $state(
    typeof localStorage !== "undefined" ? localStorage.getItem("theme") !== "light" : true,
  );

  $effect(() => {
    document.documentElement.classList.toggle("dark", dark);
    localStorage.setItem("theme", dark ? "dark" : "light");
  });
</script>

<button
  type="button"
  class="inline-flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground hover:bg-accent hover:text-accent-foreground"
  title={dark ? "Switch to light mode" : "Switch to dark mode"}
  aria-label="Toggle theme"
  onclick={() => (dark = !dark)}
>
  {#if dark}
    <Icon name="sun" class="h-4 w-4" />
  {:else}
    <Icon name="moon" class="h-4 w-4" />
  {/if}
</button>
