// frontend/src/components/chat/ChatMessageRow.tsx
import { isThoughtStreamEntry, type ChatEntry } from "../../protocol/chatEntry";
import type { ObservableItem } from "../../utils/observableCollection";
import { useObservableValue } from "../../hooks/useObservable";
import { AssistantMessageRow } from "./rows/AssistantMessageRow";
import { CheckpointSummaryRow } from "./rows/CheckpointSummaryRow";
import { ThoughtTripletRow } from "./rows/ThoughtTripletRow";
import { ToolRunRow } from "./rows/ToolRunRow";
import { UserMessageRow } from "./rows/UserMessageRow";

export type ThoughtTripletRefs = {
  streamEntry$?: ObservableItem<ChatEntry>;
  actionEntry?: ChatEntry;
};

type ChatMessageRowProps = {
  entry$: ObservableItem<ChatEntry>;
  conversationId: string;
  thoughtTripletsById?: ReadonlyMap<string, ThoughtTripletRefs>;
};

export function messageRowKey(entry$: ObservableItem<ChatEntry>): string {
  return `entry-${entry$.id}`;
}

/** Renders one ChatEntry row by `entry.type`. */
export function ChatMessageRow({ entry$, conversationId, thoughtTripletsById }: ChatMessageRowProps) {
  const entry = useObservableValue(entry$);
  if (entry.type === "user-message") {
    return <UserMessageRow entry={entry} />;
  }
  // Triplets are anchored at the thought-prepare row so chat order matches
  // thought-start order rather than stream-arrival order (which can race).
  if (entry.type === "thought-prepare") {
    const refs = thoughtTripletsById?.get(entry.thoughtId);
    return (
      <ThoughtTripletRow
        prepareEntry={entry}
        streamEntry$={refs?.streamEntry$}
        conversationId={conversationId}
        actionEntry={refs?.actionEntry}
      />
    );
  }
  // Stream and action entries are rendered inside their prepare-anchored triplet.
  if (isThoughtStreamEntry(entry) || entry.type === "thought-action") {
    if (import.meta.env.DEV) {
      console.warn("[chat] thought step row reached ChatMessageRow directly; expected prepare-anchored triplet grouping", {
        entryType: entry.type,
        entryId: entry.id,
        thoughtId: entry.thoughtId,
      });
    }
    return null;
  }
  if (entry.type === "tool-invocation") {
    return <ToolRunRow entry={entry} />;
  }
  if (entry.type === "assistant-message") {
    return <AssistantMessageRow entry={entry} conversationId={conversationId} />;
  }
  if (entry.type === "checkpoint-summary") {
    return <CheckpointSummaryRow entry={entry} />;
  }
  const _exhaustive: never = entry;
  void _exhaustive;
  return null;
}

// frontend3/src/components/chat/ChatMessageRow.svelte
<script lang="ts">
  import { isThoughtStreamEntry, type ChatEntry } from "@/protocol/chatEntry";
  import type { ThoughtTripletRefs } from "@/lib/thoughtTriplets";
  import type { ObservableItem } from "@/utils/observableCollection";
  import type { LinkedChatEntry } from "@/lib/linkedChatEntry";
  import AssistantMessageRow from "./rows/AssistantMessageRow.svelte";
  import ThoughtTripletRow from "./rows/ThoughtTripletRow.svelte";
  import ToolRunRow from "./rows/ToolRunRow.svelte";
  import CheckpointSummaryRow from "./rows/CheckpointSummaryRow.svelte";
  import UserMessageRow from "./rows/UserMessageRow.svelte";

  let {
    entry$,
    conversationId,
    thoughtTripletsById,
  }: {
    entry$: ObservableItem<LinkedChatEntry>;
    conversationId: string;
    thoughtTripletsById: ReadonlyMap<string, ThoughtTripletRefs>;
  } = $props();

  let entry = $state<ChatEntry | null>(null);

  $effect(() => {
    const row$ = entry$;
    entry = row$.get();
    return row$.subscribe(() => {
      entry = row$.get();
    });
  });
</script>

{#if entry}
  {#if entry.type === "user-message"}
    <UserMessageRow {entry} {conversationId} />
  {:else if entry.type === "thought-prepare"}
    {@const refs = thoughtTripletsById.get(entry.thoughtId)}
    <ThoughtTripletRow
      prepareEntry={entry}
      {conversationId}
      streamEntry$={refs?.streamEntry$}
      actionEntry={refs?.actionEntry ?? null}
    />
  {:else if isThoughtStreamEntry(entry) || entry.type === "thought-action"}
    <!-- rendered inside prepare-anchored triplet -->
  {:else if entry.type === "assistant-message"}
    <AssistantMessageRow {entry} {conversationId} />
  {:else if entry.type === "tool-invocation"}
    <ToolRunRow {entry} />
  {:else if entry.type === "checkpoint-summary"}
    <CheckpointSummaryRow {entry} />
  {/if}
{/if}
