// frontend/src/components/chat/BranchSelector.svelte
<script lang="ts">
  import { getChatSessionContext } from "@/lib/chatSessionContext";
  import { notifyError } from "@/utils/toast";

  let { entryId }: { entryId: string } = $props();

  const session = getChatSessionContext();
  let switching = $state(false);

  const siblings = $derived(session.siblingsOf(entryId));
  const activeIndex = $derived(siblings.findIndex((s) => s.isChosen));
  const hasBranches = $derived(siblings.length > 1 && activeIndex >= 0);

  async function switchByOffset(offset: -1 | 1): Promise<void> {
    if (!hasBranches || switching) return;
    const nextIndex = (activeIndex + offset + siblings.length) % siblings.length;
    const sibling = siblings[nextIndex];
    if (!sibling) return;
    switching = true;
    try {
      await session.switchToBranch(sibling.id);
    } catch (e) {
      notifyError(`Failed to switch branch: ${e instanceof Error ? e.message : String(e)}`);
    } finally {
      switching = false;
    }
  }
</script>

{#if hasBranches}
  <span
    data-testid="branch-selector"
    class="inline-flex items-center gap-0.5 rounded bg-secondary/60 px-1 py-0.5 text-[10px] text-muted-foreground"
    role="group"
  >
    <button
      type="button"
      disabled={switching}
      onclick={(e) => {
        e.stopPropagation();
        void switchByOffset(-1);
      }}
      class="transition-colors hover:text-foreground disabled:opacity-50"
      aria-label="Previous branch"
    >
      <svg class="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="m15 18-6-6 6-6" />
      </svg>
    </button>
    <span class="font-mono tabular-nums">{activeIndex + 1}/{siblings.length}</span>
    <button
      type="button"
      disabled={switching}
      onclick={(e) => {
        e.stopPropagation();
        void switchByOffset(1);
      }}
      class="transition-colors hover:text-foreground disabled:opacity-50"
      aria-label="Next branch"
    >
      <svg class="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="m9 18 6-6-6-6" />
      </svg>
    </button>
  </span>
{/if}

// frontend/src/components/chat/BranchSelector.tsx
import { useState } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { useChatSessionContext } from "@/hooks/chatSessionContext";
import { notifyError } from "@/utils/toast";

export function useSiblingBranches(entryId: string | null | undefined) {
  const { sessionStore, switchToBranch } = useChatSessionContext();
  const [switching, setSwitching] = useState(false);

  const siblings = entryId ? sessionStore.siblingsOf(entryId) : [];
  const activeIndex = siblings.findIndex((sibling) => sibling.isChosen);
  const hasBranches = siblings.length > 1 && activeIndex >= 0;

  async function switchByOffset(offset: -1 | 1) {
    if (!hasBranches || switching) return;
    const nextIndex = (activeIndex + offset + siblings.length) % siblings.length;
    const sibling = siblings[nextIndex];
    if (!sibling) return;
    setSwitching(true);
    try {
      await switchToBranch(sibling.id);
    } catch (e) {
      notifyError(`Failed to switch branch: ${e instanceof Error ? e.message : String(e)}`);
    } finally {
      setSwitching(false);
    }
  }

  return { siblings, activeIndex, hasBranches, switching, switchByOffset };
}

export function BranchBadge({ entryId }: { entryId: string | null | undefined }) {
  const { siblings, activeIndex, hasBranches } = useSiblingBranches(entryId);
  if (!hasBranches) return null;
  return (
    <span className="inline-flex shrink-0 items-center rounded bg-secondary/60 px-1 py-0.5 font-mono text-[9px] tabular-nums text-muted-foreground">
      {activeIndex + 1}/{siblings.length}
    </span>
  );
}

export function BranchSelector({ entryId }: { entryId: string | null | undefined }) {
  const { siblings, activeIndex, hasBranches, switching, switchByOffset } = useSiblingBranches(entryId);
  if (!hasBranches) return null;
  return (
    <div
      data-testid="branch-selector"
      className="inline-flex items-center gap-0.5 rounded bg-secondary/60 px-1 py-0.5 text-[10px] text-muted-foreground"
      onClick={(e) => e.stopPropagation()}
    >
      <button
        type="button"
        disabled={switching}
        onClick={() => {
          void switchByOffset(-1);
        }}
        className="transition-colors hover:text-foreground disabled:opacity-50"
        aria-label="Previous branch"
      >
        <ChevronLeft className="h-3 w-3" />
      </button>
      <span className="font-mono tabular-nums">
        {activeIndex + 1}/{siblings.length}
      </span>
      <button
        type="button"
        disabled={switching}
        onClick={() => {
          void switchByOffset(1);
        }}
        className="transition-colors hover:text-foreground disabled:opacity-50"
        aria-label="Next branch"
      >
        <ChevronRight className="h-3 w-3" />
      </button>
    </div>
  );
}
