// frontend/src/components/chat/ChatComposer.tsx
import { useRef, type Dispatch, type RefObject, type SetStateAction } from "react";
import type { MessageSendMode } from "./MessageComposer";
import { useNavigate, useSearchParams } from "react-router-dom";
import { cancelPendingMessage, createConversation, uploadFile } from "../../api/client";
import type { ChatAttachment } from "../../protocol/chatEntry";
import type { LlmRef } from "../../../../backend/src/contracts/llm";
import type { PendingMessage } from "@/lib/chatSessionStore";
import { ChatAgentToolbar, type ChatAgentSelection } from "./ChatAgentToolbar";
import { AttachmentChips, type SelectedAttachment } from "./AttachmentChips";
import { MessageComposer } from "./MessageComposer";
import { QueuedMessageChips } from "./QueuedMessageChips";
import { defaultAttachmentMode, sendMessageToConversation } from "./sendMessage";

type ChatComposerProps = {
  conversationId: string | null;
  composerTextareaRef: RefObject<HTMLTextAreaElement | null>;
  input: string;
  setInput: (value: string) => void;
  selectedFiles: SelectedAttachment[];
  setSelectedFiles: Dispatch<SetStateAction<SelectedAttachment[]>>;
  previewUrls: string[];
  agentSelection: ChatAgentSelection;
  onAgentSelectionChange: (selection: ChatAgentSelection) => void;
  canSend: boolean;
  appendOptimisticUserMessage: (args: {
    conversationId: string;
    text: string;
    agentId: string;
    modelPresetId: number | null;
    llm?: LlmRef;
    attachments: ChatAttachment[];
  }) => { rowId: string; clientRequestId: string; parentId: string | null } | null;
  onSent: (optimisticRowId: string) => void;
  agentRunning?: boolean;
  pendingMessages?: PendingMessage[];
};

export function ChatComposer({
  conversationId,
  composerTextareaRef,
  input,
  setInput,
  selectedFiles,
  setSelectedFiles,
  previewUrls,
  agentSelection,
  onAgentSelectionChange,
  canSend,
  appendOptimisticUserMessage,
  onSent,
  agentRunning = false,
  pendingMessages = [],
}: ChatComposerProps) {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();

  return (
    <MessageComposer
      textareaRef={composerTextareaRef}
      agentRunning={agentRunning}
      value={input}
      onValueChange={setInput}
      onPaste={(e) => {
        const items = Array.from(e.clipboardData?.items ?? []);
        const images: SelectedAttachment[] = [];
        for (const item of items) {
          if (item.kind !== "file" || !item.type.startsWith("image/")) continue;
          const file = item.getAsFile();
          if (file) images.push({ file, mode: defaultAttachmentMode(file) });
        }
        if (images.length > 0) {
          setSelectedFiles((prev) => [...prev, ...images]);
        }
      }}
      fileInputRef={fileInputRef}
      onFileInputChange={(e) => {
        const files = Array.from(e.currentTarget.files ?? []);
        if (files.length === 0) return;
        const wrapped: SelectedAttachment[] = files.map((file) => ({ file, mode: defaultAttachmentMode(file) }));
        setSelectedFiles((prev) => [...prev, ...wrapped]);
        e.currentTarget.value = "";
      }}
      onPickFiles={() => fileInputRef.current?.click()}
      canSend={canSend}
      placeholder="Send a message…"
      selectionSlot={<ChatAgentToolbar onSelectionChange={onAgentSelectionChange} embedded />}
      queuedSlot={
        conversationId && pendingMessages.length > 0 ? (
          <QueuedMessageChips
            messages={pendingMessages}
            onCancel={(clientRequestId) => cancelPendingMessage(conversationId, clientRequestId)}
          />
        ) : undefined
      }
      attachmentsSlot={
        selectedFiles.length > 0 ? (
          <AttachmentChips
            files={selectedFiles}
            previewUrls={previewUrls}
            onChangeMode={(idx, next) =>
              setSelectedFiles((prev) => prev.map((entry, x) => (x === idx ? { ...entry, mode: next } : entry)))
            }
            onRemove={(idx) => setSelectedFiles((prev) => prev.filter((_, x) => x !== idx))}
          />
        ) : undefined
      }
      onSendAsync={({ steer, enqueue }: MessageSendMode) => {
        return (async () => {
          const text = input.trim();
          if (!text && selectedFiles.length === 0) return { ok: false };
          const uploadedAttachments: ChatAttachment[] = [];
          for (const { file, mode } of selectedFiles) {
            const uploaded = await uploadFile(file);
            uploadedAttachments.push({ ...uploaded.attachment, mode });
          }

          // Enqueue: don't add to the transcript yet — it posts after the
          // current run finishes (server resolves the parent at drain time).
          // It surfaces as a queued chip until then.
          if (enqueue && conversationId) {
            setInput("");
            setSelectedFiles([]);
            return sendMessageToConversation(
              conversationId,
              text,
              agentSelection.agentId,
              agentSelection.llm,
              agentSelection.modelPresetId,
              uploadedAttachments.map((x) => ({ id: x.id, mode: x.mode })),
              null,
              crypto.randomUUID(),
              { enqueue: true },
            );
          }

          const optimisticInput = {
            text,
            agentId: agentSelection.agentId,
            modelPresetId: agentSelection.modelPresetId,
            ...(agentSelection.llm ? { llm: agentSelection.llm } : {}),
            attachments: uploadedAttachments,
          };
          if (!conversationId) {
            const created = await createConversation();
            const cid = created.id;
            setInput("");
            setSelectedFiles([]);
            const result = await sendMessageToConversation(
              cid,
              text,
              agentSelection.agentId,
              agentSelection.llm,
              agentSelection.modelPresetId,
              uploadedAttachments.map((x) => ({ id: x.id, mode: x.mode })),
              null,
              crypto.randomUUID(),
              { steer },
            );
            const q = searchParams.toString();
            navigate(
              {
                pathname: `/chat/${encodeURIComponent(cid)}`,
                search: q ? `?${q}` : "",
              },
              { replace: true },
            );
            return result;
          }

          const optimistic = appendOptimisticUserMessage({ conversationId, ...optimisticInput });
          if (!optimistic) return { ok: false };
          onSent(optimistic.rowId);
          setInput("");
          setSelectedFiles([]);
          return sendMessageToConversation(
            conversationId,
            text,
            agentSelection.agentId,
            agentSelection.llm,
            agentSelection.modelPresetId,
            uploadedAttachments.map((x) => ({ id: x.id, mode: x.mode })),
            optimistic.parentId,
            optimistic.clientRequestId,
            { steer },
          );
        })();
      }}
    />
  );
}

// frontend/src/components/chat/ChatComposer.svelte
<script lang="ts">
  import { cancelPendingMessage, createConversation, uploadFile } from "@/api/client";
  import type { ChatAttachment } from "@/protocol/chatEntry";
  import type { LlmRef } from "../../../../backend/src/contracts/llm";
  import { getChatSessionStore, retainChatSessionLive } from "@/lib/chatSessionRegistry";
  import type { OptimisticUserMessage } from "@/lib/chatSessionState.svelte";
  import { conversationHasRunningTask, ensureTasksStream } from "@/lib/tasksStore.svelte";
  import { agentIdFromSearch, replacePath } from "@/lib/router";
  import { onMount } from "svelte";
  import type { ChatAgentSelection } from "./ChatAgentToolbar.svelte";
  import AttachmentChips, { type SelectedAttachment } from "./AttachmentChips.svelte";
  import MessageComposer from "./MessageComposer.svelte";
  import QueuedMessageChips from "./QueuedMessageChips.svelte";
  import type { PendingMessage } from "@/lib/chatSessionStore";
  import { compileUserMessageOverrides } from "@/lib/chatToolOverrides";
  import { getChatToolDraft } from "@/lib/chatToolDraft.svelte";
  import { defaultAttachmentMode, sendMessageToConversation, type MessageSendMode } from "./sendMessage";

  let {
    conversationId,
    search,
    pendingMessages = [],
    appendOptimisticUserMessage,
    onSent,
    textareaRef = $bindable(null),
  }: {
    conversationId: string | null;
    search: string;
    pendingMessages?: PendingMessage[];
    appendOptimisticUserMessage: (input: {
      conversationId: string;
      text: string;
      agentId: string;
      llm?: LlmRef;
      modelPresetId?: number | null;
      attachments?: ChatAttachment[];
    }) => OptimisticUserMessage | null;
    onSent?: (optimisticRowId: string) => void;
    textareaRef?: HTMLTextAreaElement | null;
  } = $props();

  let input = $state("");
  let sending = $state(false);
  let selectedFiles = $state<SelectedAttachment[]>([]);
  let previewUrls = $state<string[]>([]);
  let agentSelection = $state<ChatAgentSelection>({ agentId: "", llm: null, modelPresetId: null });

  onMount(() => ensureTasksStream());

  const urlAgentId = $derived(agentIdFromSearch(search));
  const effectiveAgentId = $derived(agentSelection.agentId.trim() || urlAgentId);
  const canSend = $derived((input.trim().length > 0 || selectedFiles.length > 0) && Boolean(effectiveAgentId));
  const agentRunning = $derived(conversationHasRunningTask(conversationId));

  $effect(() => {
    const urls = selectedFiles.map(({ file }) =>
      file.type.startsWith("image/") || file.type === "application/pdf" ? URL.createObjectURL(file) : "",
    );
    previewUrls = urls;
    return () => {
      for (const url of urls) {
        if (url) URL.revokeObjectURL(url);
      }
    };
  });

  function addFiles(files: File[]): void {
    if (files.length === 0) return;
    const wrapped = files.map((file) => ({ file, mode: defaultAttachmentMode(file) }));
    selectedFiles = [...selectedFiles, ...wrapped];
  }

  async function onSend(mode: MessageSendMode): Promise<void> {
    if (!canSend || sending) return;
    sending = true;
    const text = input.trim();
    const clientRequestId = crypto.randomUUID();
    const agentId = effectiveAgentId;
    const { llm, modelPresetId } = agentSelection;
    const overrides = compileUserMessageOverrides(getChatToolDraft());
    const sendOpts = {
      ...(mode.steer ? { steer: true as const } : {}),
      ...(mode.enqueue ? { enqueue: true as const } : {}),
      ...(overrides ? { overrides } : {}),
    };

    try {
      const uploadedAttachments: ChatAttachment[] = [];
      for (const { file, mode: attachmentMode } of selectedFiles) {
        const uploaded = await uploadFile(file);
        uploadedAttachments.push({ ...uploaded.attachment, mode: attachmentMode });
      }
      const postAttachments = uploadedAttachments.map((x) => ({ id: x.id, mode: x.mode }));

      if (mode.enqueue && conversationId) {
        input = "";
        selectedFiles = [];
        await sendMessageToConversation(
          conversationId,
          text,
          agentId,
          llm,
          modelPresetId,
          postAttachments,
          null,
          clientRequestId,
          sendOpts,
        );
        return;
      }

      if (!conversationId) {
        const created = await createConversation();
        const cid = String(created.id || "").trim();
        if (!cid) throw new Error("createConversation returned no id");
        retainChatSessionLive();
        getChatSessionStore(cid);
        input = "";
        selectedFiles = [];
        await sendMessageToConversation(
          cid,
          text,
          agentId,
          llm,
          modelPresetId,
          postAttachments,
          null,
          clientRequestId,
          sendOpts,
        );
        replacePath(`/chat/${encodeURIComponent(cid)}${search}`);
        return;
      }

      if (!mode.enqueue) {
        const optimistic = appendOptimisticUserMessage({
          conversationId,
          text,
          agentId,
          llm: llm ?? undefined,
          modelPresetId,
          attachments: uploadedAttachments,
        });
        if (!optimistic) throw new Error("appendOptimisticUserMessage failed");
        onSent?.(optimistic.rowId);
        input = "";
        selectedFiles = [];
        await sendMessageToConversation(
          conversationId,
          text,
          agentId,
          llm,
          modelPresetId,
          postAttachments,
          optimistic.parentId,
          optimistic.clientRequestId,
          sendOpts,
        );
      }
    } catch (err) {
      console.error("[ChatComposer] send failed", err);
      input = text;
      throw err;
    } finally {
      sending = false;
    }
  }
</script>

<MessageComposer
  bind:textareaRef
  value={input}
  onValueChange={(v) => (input = v)}
  {canSend}
  {agentRunning}
  {sending}
  onSend={onSend}
  onAgentSelectionChange={(sel) => (agentSelection = sel)}
  onPasteFiles={addFiles}
  onFileInputChange={addFiles}
>
  {#snippet queuedSlot()}
    {#if conversationId && pendingMessages.length > 0}
      <QueuedMessageChips
        messages={pendingMessages}
        onCancel={(clientRequestId) => void cancelPendingMessage(conversationId, clientRequestId)}
      />
    {/if}
  {/snippet}
  {#snippet attachmentsSlot()}
    {#if selectedFiles.length > 0}
      <AttachmentChips
        files={selectedFiles}
        {previewUrls}
        onChangeMode={(idx, next) => {
          selectedFiles = selectedFiles.map((entry, x) => (x === idx ? { ...entry, mode: next } : entry));
        }}
        onRemove={(idx) => {
          selectedFiles = selectedFiles.filter((_, x) => x !== idx);
        }}
      />
    {/if}
  {/snippet}
</MessageComposer>
