// frontend3/src/components/ThemeToggle.svelte
<script lang="ts">
  let dark = $state(
    typeof localStorage !== "undefined" ? localStorage.getItem("theme") !== "light" : true,
  );

  $effect(() => {
    document.documentElement.classList.toggle("dark", dark);
    localStorage.setItem("theme", dark ? "dark" : "light");
  });
</script>

<button
  type="button"
  class="inline-flex h-7 w-7 items-center justify-center rounded-md text-muted-foreground hover:bg-muted hover:text-foreground"
  title={dark ? "Switch to light mode" : "Switch to dark mode"}
  aria-label="Toggle theme"
  onclick={() => (dark = !dark)}
>
  {dark ? "☀" : "☾"}
</button>

// frontend2/src/components/ThemeToggle.tsx
import { Moon, Sun } from "lucide-react";
import { useEffect, useState } from "react";

export function ThemeToggle() {
  const [dark, setDark] = useState(() => {
    if (typeof window === "undefined") return true;
    return localStorage.getItem("theme") !== "light";
  });

  useEffect(() => {
    document.documentElement.classList.toggle("dark", dark);
    localStorage.setItem("theme", dark ? "dark" : "light");
  }, [dark]);

  return (
    <button
      onClick={() => setDark((d) => !d)}
      className="p-1.5 rounded-md hover:bg-secondary transition-colors text-muted-foreground"
      title={dark ? "Switch to light mode" : "Switch to dark mode"}
    >
      {dark ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
    </button>
  );
}
