// frontend3/src/components/chat/rows/thoughtTriplet/ContextStep.svelte
<script lang="ts">
  import { reprocessThoughtContext } from "@/api/client";
  import type { ThoughtPrepareEntry, ThoughtStreamEntry } from "@/protocol/chatEntry";
  import ModelDropdown from "@/components/ui/ModelDropdown.svelte";
  import ZodJsonEditor from "@/components/ui/ZodJsonEditor.svelte";
  import { createLlmProvidersQuery } from "@/hooks/queries/referenceData";
  import { LlmRequestSchema } from "@/lib/editorSchemas";
  import { getChatSessionContext } from "@/lib/chatSessionContext";
  import { buildModelGroups } from "@/pages/settings/helpers";
  import { notifyError } from "@/utils/toast";
  import ReadOnlySection from "../ReadOnlySection.svelte";

  let {
    prepareEntry,
    stream,
    conversationId,
  }: {
    prepareEntry: ThoughtPrepareEntry;
    stream: ThoughtStreamEntry;
    conversationId: string;
  } = $props();

  const session = getChatSessionContext();
  const providersQuery = createLlmProvidersQuery();
  const modelGroups = $derived(buildModelGroups(providersQuery.data ?? []));

  let isEditing = $state(false);
  let isSaving = $state(false);
  let promptValid = $state(false);

  const prompt = $derived((prepareEntry.requestText ?? stream.llmRequest ?? "").trim());
  const currentProviderId = $derived(String(prepareEntry.llm?.providerId ?? stream.llm?.providerId ?? "").trim());
  const currentModel = $derived(String(prepareEntry.llm?.model ?? stream.llm?.model ?? "").trim());

  let editedPrompt = $state("");
  let selectedProviderId = $state("");
  let selectedModel = $state("");

  $effect(() => {
    if (isEditing) return;
    editedPrompt = prompt;
    selectedProviderId = currentProviderId;
    selectedModel = currentModel;
  });

  const canApply = $derived(
    promptValid && selectedProviderId.trim().length > 0 && selectedModel.trim().length > 0 && !isSaving,
  );

  async function applyEdit(): Promise<void> {
    if (!canApply) return;
    isSaving = true;
    try {
      const result = await reprocessThoughtContext(conversationId, prepareEntry.id, {
        editedRequestText: editedPrompt.trim(),
        llm: { providerId: selectedProviderId.trim(), model: selectedModel.trim() },
      });
      await session.setActiveLeaf(result.data.leafEntryId);
      isEditing = false;
    } catch (error) {
      notifyError(`Failed to reprocess context: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      isSaving = false;
    }
  }
</script>

<div class="mt-1.5 ml-1 space-y-2 text-xs">
  <div class="flex items-center justify-between gap-2 text-[10px] text-muted-foreground">
    <span>{currentProviderId && currentModel ? `model: ${currentProviderId}/${currentModel}` : "model: unknown"}</span>
    <button
      type="button"
      class="ml-auto flex items-center gap-1 rounded px-1.5 py-0.5 text-[11px] text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
      onclick={() => (isEditing = !isEditing)}
      title="Edit context and branch"
    >
      <svg class="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z" />
      </svg>
      {isEditing ? "Close edit" : "Edit"}
    </button>
  </div>
  {#if isEditing}
    <div class="space-y-1.5">
      <div class="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">Model</div>
      <ModelDropdown
        value={selectedModel}
        onChange={(model, providerId) => {
          selectedModel = model;
          if (providerId) selectedProviderId = String(providerId).trim();
        }}
        groups={modelGroups}
      />
      <div class="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">Prompt</div>
      <ZodJsonEditor
        schema={LlmRequestSchema}
        value={editedPrompt}
        onchange={(v: string) => (editedPrompt = v)}
        onValidityChange={(v: boolean) => (promptValid = v)}
        height={260}
        onSubmitShortcut={() => void applyEdit()}
      />
      <div class="flex justify-end gap-1.5">
        <button
          type="button"
          class="rounded border border-border/70 px-2 py-1 text-[10px] font-medium text-muted-foreground transition-colors hover:bg-secondary/70 hover:text-foreground"
          onclick={() => {
            editedPrompt = prompt;
            selectedProviderId = currentProviderId;
            selectedModel = currentModel;
            isEditing = false;
          }}
          disabled={isSaving}
        >
          Cancel
        </button>
        <button
          type="button"
          class="rounded border border-primary/50 px-2 py-1 text-[10px] font-medium text-primary transition-colors hover:bg-primary/10 disabled:cursor-not-allowed disabled:opacity-50"
          onclick={() => void applyEdit()}
          disabled={!canApply}
        >
          {isSaving ? "Applying…" : "Apply"}
        </button>
      </div>
    </div>
  {:else}
    <ReadOnlySection label="Prompt" value={prompt} />
  {/if}
</div>

// frontend/src/components/chat/rows/thoughtTriplet/ContextStep.tsx
import { useEffect, useMemo, useState } from "react";
import { Pencil } from "lucide-react";
import { reprocessThoughtContext } from "@/api/client";
import type { ThoughtPrepareEntry, ThoughtStreamEntry } from "@/protocol/chatEntry";
import { useChatSessionContext } from "@/hooks/chatSessionContext";
import { notifyError } from "@/utils/toast";
import { useLlmSettings } from "@/hooks/llmSettingsContext";
import { ModelSelector } from "@/components/ui/ModelSelector";
import { ZodJsonEditor } from "@/components/ui/ZodJsonEditor";
import { LlmRequestSchema } from "@/lib/editorSchemas";
import { ReadOnlySection } from "./ReadOnlySection";

export function ContextStep({
  prepareEntry,
  stream,
  conversationId,
}: {
  prepareEntry: ThoughtPrepareEntry;
  stream: ThoughtStreamEntry;
  conversationId: string;
}) {
  const prompt = useMemo(() => (prepareEntry.requestText ?? stream.llmRequest ?? "").trim(), [prepareEntry.requestText, stream.llmRequest]);
  const currentProviderId = String(prepareEntry.llm?.providerId ?? stream.llm?.providerId ?? "").trim();
  const currentModel = String(prepareEntry.llm?.model ?? stream.llm?.model ?? "").trim();
  const [isEditing, setIsEditing] = useState(false);
  const [editedPrompt, setEditedPrompt] = useState(prompt);
  const [selectedProviderId, setSelectedProviderId] = useState(currentProviderId);
  const [selectedModel, setSelectedModel] = useState(currentModel);
  const [promptValid, setPromptValid] = useState(false);
  const { modelGroups } = useLlmSettings();
  const { setActiveLeaf } = useChatSessionContext();
  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => {
    if (isEditing) return;
    setEditedPrompt(prompt);
    setSelectedProviderId(currentProviderId);
    setSelectedModel(currentModel);
  }, [currentModel, currentProviderId, isEditing, prompt]);

  const canApply =
    promptValid &&
    selectedProviderId.trim().length > 0 &&
    selectedModel.trim().length > 0 &&
    !isSaving;

  const applyEdit = async () => {
    if (!canApply) return;
    setIsSaving(true);
    try {
      const result = await reprocessThoughtContext(conversationId, prepareEntry.id, {
        editedRequestText: editedPrompt.trim(),
        llm: { providerId: selectedProviderId.trim(), model: selectedModel.trim() },
      });
      await setActiveLeaf(result.data.leafEntryId);
      setIsEditing(false);
    } catch (error) {
      const detail = error instanceof Error ? error.message : String(error);
      notifyError(`Failed to reprocess context: ${detail}`);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="mt-1.5 ml-1 space-y-2 text-xs">
      <div className="flex items-center justify-between gap-2 text-[10px] text-muted-foreground">
        <span>{currentProviderId && currentModel ? `model: ${currentProviderId}/${currentModel}` : "model: unknown"}</span>
        <button
          type="button"
          className="ml-auto flex items-center gap-1 rounded px-1.5 py-0.5 text-[11px] text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
          onClick={() => setIsEditing((v) => !v)}
          title="Edit context and branch"
        >
          <Pencil className="h-3 w-3" />
          {isEditing ? "Close edit" : "Edit"}
        </button>
      </div>
      {isEditing ? (
        <div className="space-y-1.5">
          <div className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">Model</div>
          <ModelSelector
            value={selectedModel}
            onChange={(model, providerId) => {
              setSelectedModel(model);
              if (providerId) setSelectedProviderId(String(providerId).trim());
            }}
            modelGroups={modelGroups}
            placeholder="Select model"
            searchPlaceholder="Search model"
          />
          <div className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">Prompt</div>
          <ZodJsonEditor
            schema={LlmRequestSchema}
            value={editedPrompt}
            onChange={setEditedPrompt}
            onValidityChange={setPromptValid}
            height={260}
          />
          <div className="flex justify-end gap-1.5">
            <button
              type="button"
              className="rounded border border-border/70 px-2 py-1 text-[10px] font-medium text-muted-foreground transition-colors hover:bg-secondary/70 hover:text-foreground"
              onClick={() => {
                setEditedPrompt(prompt);
                setSelectedProviderId(currentProviderId);
                setSelectedModel(currentModel);
                setIsEditing(false);
              }}
              disabled={isSaving}
            >
              Cancel
            </button>
            <button
              type="button"
              className="rounded border border-primary/50 px-2 py-1 text-[10px] font-medium text-primary transition-colors hover:bg-primary/10 disabled:cursor-not-allowed disabled:opacity-50"
              onClick={() => {
                void applyEdit();
              }}
              disabled={!canApply}
            >
              {isSaving ? "Applying..." : "Apply"}
            </button>
          </div>
        </div>
      ) : (
        <ReadOnlySection label="Prompt" value={prompt} />
      )}
    </div>
  );
}
