// frontend/src/components/chat/rows/StepChip.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import RowIcon from "../RowIcon.svelte";

  let {
    icon,
    label,
    meta = "",
    metaSlot,
    badge,
    active,
    align = "left",
    testId,
    onclick,
  }: {
    icon: Snippet;
    label: string;
    meta?: string;
    metaSlot?: Snippet;
    badge?: Snippet;
    active: boolean;
    align?: "left" | "right";
    testId?: string;
    onclick: () => void;
  } = $props();

  const hasMeta = $derived(meta.trim().length > 0 || Boolean(metaSlot));
</script>

<div
  role="button"
  tabindex="0"
  data-testid={testId}
  onclick={onclick}
  onkeydown={(e) => {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      onclick();
    }
  }}
  class="inline-flex min-w-0 flex-1 cursor-pointer items-center gap-1 overflow-hidden rounded px-2 py-1 transition-colors {align === 'right'
    ? 'justify-end text-right'
    : 'justify-start text-left'} {active ? 'bg-secondary text-foreground' : 'hover:bg-secondary/60 hover:text-foreground'}"
>
  <span class="inline-flex h-3.5 w-3.5 shrink-0 items-center justify-center">
    {@render icon()}
  </span>
  <span class="inline-flex min-w-0 items-center gap-1 {align === 'right' ? '' : 'flex-1'}">
    {#if label}
      <span class="truncate font-medium">{label}</span>
    {/if}
    {#if hasMeta}
      <span class="min-w-0 truncate font-mono opacity-60 inline-flex items-center gap-1 flex-wrap">
        {#if label && (hasMeta)}<span>·</span>{/if}
        {#if metaSlot}
          {@render metaSlot()}
        {:else}
          {meta}
        {/if}
      </span>
    {/if}
  </span>
  {#if badge}
    <span class="shrink-0">{@render badge()}</span>
  {/if}
  <RowIcon name="chevron-down" class="h-3.5 w-3.5 shrink-0 opacity-60 transition-transform {active ? 'rotate-180' : ''}" />
</div>

// frontend/src/components/chat/rows/thoughtTriplet/StepChip.tsx
import { ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

export function StepChip({
  icon,
  label,
  meta,
  badge,
  active,
  align = "left",
  onClick,
}: {
  icon: React.ReactNode;
  label: string;
  meta?: string;
  badge?: React.ReactNode;
  active: boolean;
  align?: "left" | "right";
  onClick: () => void;
}) {
  const hasMeta = typeof meta === "string" && meta.trim().length > 0;
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "inline-flex min-w-0 flex-1 items-center gap-1 overflow-hidden rounded px-2 py-1 transition-colors",
        align === "right" ? "justify-end text-right" : "justify-start text-left",
        active ? "bg-secondary text-foreground" : "hover:bg-secondary/60 hover:text-foreground",
      )}
    >
      <span className="inline-flex h-3.5 w-3.5 shrink-0 items-center justify-center">{icon}</span>
      <span className={cn("inline-flex min-w-0 items-center gap-1", align === "right" ? "" : "flex-1")}>
        {label ? <span className="truncate font-medium">{label}</span> : null}
        {hasMeta ? <span className="truncate opacity-60">{label ? `· ${meta}` : meta}</span> : null}
      </span>
      {badge ? <span className="shrink-0">{badge}</span> : null}
      <ChevronDown className={cn("h-3.5 w-3.5 shrink-0 opacity-60 transition-transform", active ? "rotate-180" : "")} />
    </button>
  );
}

export function Connector() {
  return <span className="self-center opacity-60">→</span>;
}

export function TinyProgressCircle() {
  return <span className="h-3 w-3 animate-spin rounded-full border border-current border-t-transparent" aria-hidden="true" />;
}
