// frontend/src/App.tsx
import { Navigate, NavLink, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import { useMemo, useState } from "react";
import { buttonVariants } from "@/components/ui/button";
import { ResizableSidePanel } from "@/components/ui/ResizableSidePanel";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import { ConversationSidebar } from "./components/ConversationSidebar";
import { ErrorInboxButton } from "./components/ErrorInboxButton";
import { ThemeToggle } from "./components/ThemeToggle";
import { ToastHost } from "./components/ToastHost";
import { ChatPage } from "./pages/ChatPage";
import { ComponentsPlaygroundPage } from "./pages/playground/ComponentsPlaygroundPage";
import { SettingsPage } from "./pages/SettingsPage";

function settingsLinkTo(loc: { pathname: string; search: string }) {
  if (loc.pathname.startsWith("/settings")) {
    return { pathname: loc.pathname, search: loc.search };
  }
  const agent = new URLSearchParams(loc.search).get("agent")?.trim();
  if (agent) {
    return {
      pathname: "/settings/agents",
      search: `?agent=${encodeURIComponent(agent)}`,
    };
  }
  return { pathname: "/settings/model-providers", search: "" };
}

function chatActiveIdFromPath(pathname: string): string | null {
  if (!pathname || !pathname.startsWith("/chat")) return null;
  const rest = pathname.slice("/chat".length) || "";
  const segment = rest.startsWith("/") ? rest.slice(1).split("/")[0] : "";
  return segment === "new" || !segment ? null : segment;
}

function ChatPageShell({
  sidebarVisible,
  onToggleSidebar,
  onOpenSettings,
  settingsPressed,
}: {
  sidebarVisible: boolean;
  onToggleSidebar: () => void;
  onOpenSettings: () => void;
  settingsPressed: boolean;
}) {
  const { conversationId: raw } = useParams();
  const cid = !raw || raw === "new" ? null : String(raw);
  return (
    <ChatPage
      conversationId={cid}
      sidebarVisible={sidebarVisible}
      onToggleSidebar={onToggleSidebar}
      onOpenSettings={onOpenSettings}
      settingsPressed={settingsPressed}
    />
  );
}

export function App() {
  const navigate = useNavigate();
  const location = useLocation();
  const [chatSidebarVisible, setChatSidebarVisible] = useState(true);
  const activeConversationId = chatActiveIdFromPath(location.pathname);
  const showConversationSidebar = location.pathname.startsWith("/chat");
  const chatTab = location.pathname.startsWith("/chat");
  const settingsTab = location.pathname.startsWith("/settings");
  const playgroundTab = location.pathname.startsWith("/playground");
  const showTopHeader = !chatTab;
  const sidebarDefaultSize = useMemo(() => {
    if (typeof window === "undefined") return 14;
    const rawPercent = (300 / Math.max(1, window.innerWidth)) * 100;
    return Math.max(1, Math.min(95, rawPercent));
  }, []);
  const appRoutes = (
    <Routes>
      <Route
        path="/chat/:conversationId"
        element={
          <ChatPageShell
            sidebarVisible={chatSidebarVisible}
            onToggleSidebar={() => setChatSidebarVisible((v) => !v)}
            onOpenSettings={() => navigate(settingsLinkTo(location))}
            settingsPressed={settingsTab}
          />
        }
      />
      <Route path="/chat" element={<Navigate to="/chat/new" replace />} />
      <Route path="/permissions" element={<Navigate to="/settings/tools" replace />} />
      <Route path="/settings" element={<Navigate to="/settings/model-providers" replace />} />
      <Route path="/settings/:section" element={<SettingsPage />} />
      <Route path="/playground/components" element={<ComponentsPlaygroundPage />} />
      <Route path="*" element={<Navigate to="/chat/new" replace />} />
    </Routes>
  );

  return (
    <TooltipProvider delayDuration={300}>
      <div className="flex h-full max-h-full min-h-0 flex-col overflow-hidden bg-background">
        <ToastHost />
        {showTopHeader ? (
          <header className="flex shrink-0 flex-wrap items-center justify-between gap-2 border-b border-border bg-card/50 px-3 py-2 backdrop-blur-sm">
            <div className="flex flex-wrap items-center gap-2 md:gap-3">
              <span className="text-sm font-semibold tracking-tight text-foreground">Runvane</span>
              <nav className="flex flex-wrap gap-2">
                <NavLink
                  to="/chat/new"
                  className={cn(
                    buttonVariants({
                      variant: chatTab ? "default" : "outline",
                      size: "sm",
                    }),
                    "no-underline",
                  )}
                >
                  Chat
                </NavLink>
                <NavLink
                  to={settingsLinkTo(location)}
                  className={cn(
                    buttonVariants({
                      variant: settingsTab ? "default" : "outline",
                      size: "sm",
                    }),
                    "no-underline",
                  )}
                >
                  Settings
                </NavLink>
                <NavLink
                  to="/playground/components"
                  className={cn(
                    buttonVariants({
                      variant: playgroundTab ? "default" : "outline",
                      size: "sm",
                    }),
                    "no-underline",
                  )}
                >
                  Playground
                </NavLink>
              </nav>
            </div>
            <div className="relative flex items-center gap-1">
              <ThemeToggle />
              <ErrorInboxButton />
            </div>
          </header>
        ) : null}

        <div className="flex min-h-0 flex-1 overflow-hidden">
          {showConversationSidebar ? (
            <ResizableSidePanel
              open={chatSidebarVisible}
              onOpenChange={setChatSidebarVisible}
              defaultSize={sidebarDefaultSize}
              minSize={10}
              side={
                <div
                  className={cn(
                    "h-full min-h-0 min-w-0 overflow-hidden transition-opacity duration-200",
                    chatSidebarVisible ? "opacity-100" : "pointer-events-none opacity-0",
                  )}
                >
                  <ConversationSidebar
                    activeConversationId={activeConversationId}
                    onNewChat={() => navigate("/chat/new")}
                    onSelect={(id) => navigate(`/chat/${id}`)}
                  />
                </div>
              }
            >
              <section className="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">{appRoutes}</section>
            </ResizableSidePanel>
          ) : (
            <section className="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">{appRoutes}</section>
          )}
        </div>
      </div>
    </TooltipProvider>
  );
}

// frontend3/src/App.svelte
<script lang="ts">
  import ConversationSidebar from "@/components/sidebar/ConversationSidebar.svelte";
  import ResizableSidePanel from "@/components/ui/ResizableSidePanel.svelte";
  import ChatPage from "@/pages/ChatPage.svelte";
  import SettingsPage from "@/pages/SettingsPage.svelte";
  import ToastHost from "@/components/ToastHost.svelte";
  import ErrorInboxButton from "@/components/ErrorInboxButton.svelte";
  import ThemeToggle from "@/components/ThemeToggle.svelte";
  import { QueryClientProvider } from "@tanstack/svelte-query";
  import { queryClient } from "@/lib/queryClient";
  import {
    pathname,
    pathOnly,
    chatConversationId,
    chatSearch,
    settingsSection,
    isChatRoute,
    isSettingsRoute,
    navigate,
    settingsLinkFromSearch,
  } from "@/lib/router";
  import { fetchConversationSession } from "@/hooks/queries/conversations";
  import { retainChatSessionLive } from "@/lib/chatSessionRegistry";
  import { navBtnBase, navBtnDefault, navBtnOutline } from "@/lib/buttonClasses";
  import { onMount } from "svelte";

  let chatSidebarVisible = $state(true);
  let chatRightSidebarVisible = $state(true);

  const sidebarDefaultSize = $derived.by(() => {
    if (typeof window === "undefined") return 14;
    const rawPercent = (300 / Math.max(1, window.innerWidth)) * 100;
    return Math.max(1, Math.min(95, rawPercent));
  });

  onMount(() => {
    retainChatSessionLive();
    if ($pathOnly === "/chat") navigate(`/chat/new${$chatSearch}`);
    if ($pathOnly === "/settings") navigate(settingsLinkFromSearch($chatSearch));
    if ($pathOnly === "/permissions") navigate("/settings/tools");
  });

  $effect(() => {
    if ($pathOnly === "/permissions") navigate("/settings/tools");
  });

  $effect(() => {
    const id = $chatConversationId;
    if (!id) return;
    const rows = document.querySelectorAll("[data-conversation-row]");
    for (const row of rows) {
      const rowId = row.getAttribute("data-conversation-id");
      row.setAttribute("data-active", rowId === id ? "true" : "false");
    }
  });

  function onNewChat(): void {
    navigate(`/chat/new${$chatSearch}`);
  }

  function onSelectConversation(id: string): void {
    void fetchConversationSession(id);
    navigate(`/chat/${encodeURIComponent(id)}${$chatSearch}`);
  }
</script>

<QueryClientProvider client={queryClient}>
  <div class="flex h-dvh flex-col overflow-hidden bg-background text-foreground">
    <ToastHost />
    {#if !$isChatRoute}
      <header
        class="flex shrink-0 flex-wrap items-center justify-between gap-2 border-b border-border bg-card/50 px-3 py-2 backdrop-blur-sm"
      >
        <div class="flex flex-wrap items-center gap-2 md:gap-3">
          <span class="text-sm font-semibold tracking-tight text-foreground">Runvane</span>
          <nav class="flex flex-wrap gap-2">
            <button
              type="button"
              class="{navBtnBase} {$isChatRoute ? navBtnDefault : navBtnOutline}"
              onclick={() => navigate(`/chat/new${$chatSearch}`)}
            >
              Chat
            </button>
            <button
              type="button"
              class="{navBtnBase} {$isSettingsRoute ? navBtnDefault : navBtnOutline}"
              onclick={() => navigate(settingsLinkFromSearch($chatSearch))}
            >
              Settings
            </button>
          </nav>
        </div>
        <div class="flex items-center gap-2">
          <ErrorInboxButton />
          <ThemeToggle />
        </div>
      </header>
    {/if}

    <div class="flex min-h-0 flex-1 overflow-hidden">
      {#if $isChatRoute}
        <ResizableSidePanel
          open={chatSidebarVisible}
          onOpenChange={(open) => (chatSidebarVisible = open)}
          defaultSize={sidebarDefaultSize}
          minSize={10}
        >
          {#snippet side()}
            <ConversationSidebar
              onNewChat={onNewChat}
              onSelect={onSelectConversation}
              search={$chatSearch}
            />
          {/snippet}
          {#snippet children()}
            <main class="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">
              <ChatPage
                conversationId={$chatConversationId}
                search={$chatSearch}
                sidebarVisible={chatSidebarVisible}
                onToggleSidebar={() => (chatSidebarVisible = !chatSidebarVisible)}
                rightSidebarVisible={chatRightSidebarVisible}
                onToggleRightSidebar={() => (chatRightSidebarVisible = !chatRightSidebarVisible)}
                settingsPressed={$isSettingsRoute}
              />
            </main>
          {/snippet}
        </ResizableSidePanel>
      {:else}
        <main class="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">
          {#if $isSettingsRoute}
            <SettingsPage sectionRaw={$settingsSection} />
          {:else}
            <div class="p-8 text-sm text-muted-foreground">Unknown route {$pathname}</div>
          {/if}
        </main>
      {/if}
    </div>
  </div>
</QueryClientProvider>
