// frontend/src/pages/settings/AgentColorPicker.svelte
<script lang="ts">
  import Icon from "@/components/ui/Icon.svelte";
  import { AGENT_COLOR_DEFAULT, AGENT_COLORS, getAgentColor } from "./agentColors";

  let {
    value,
    disabled = false,
    onchange,
  }: {
    value: string | null;
    disabled?: boolean;
    onchange: (colorId: string | null) => void;
  } = $props();

  let open = $state(false);
  const current = $derived(getAgentColor(value));
</script>

<div class="relative">
  <button
    type="button"
    {disabled}
    title="Color: {current.label}"
    class="inline-flex h-9 items-center gap-1.5 rounded-md border border-input bg-muted/40 px-2 text-foreground transition-colors hover:bg-secondary/60 {disabled
      ? 'cursor-not-allowed opacity-55'
      : ''}"
    onclick={() => (open = !open)}
  >
    <span class="h-3.5 w-3.5 rounded-full {current.swatch}"></span>
    <Icon name="chevron-down" class="h-2.5 w-2.5 opacity-60" strokeWidth={2.5} />
  </button>
  {#if open && !disabled}
    <div
      class="absolute left-0 top-full z-[1400] mt-1 rounded-lg border border-border bg-popover p-2 shadow-xl"
      role="menu"
    >
      <div class="grid grid-cols-6 gap-1">
        <button
          type="button"
          title={AGENT_COLOR_DEFAULT.label}
          class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-transparent hover:bg-primary/10 {value == null
            ? 'border-primary/60 bg-primary/15'
            : ''}"
          onclick={() => {
            onchange(null);
            open = false;
          }}
        >
          <span class="h-4 w-4 rounded-full {AGENT_COLOR_DEFAULT.swatch}"></span>
        </button>
        {#each AGENT_COLORS as color (color.id)}
          <button
            type="button"
            title={color.label}
            class="inline-flex h-7 w-7 items-center justify-center rounded-md border border-transparent hover:bg-primary/10 {value === color.id
              ? 'border-primary/60 bg-primary/15'
              : ''}"
            onclick={() => {
              onchange(color.id);
              open = false;
            }}
          >
            <span class="h-4 w-4 rounded-full {color.swatch}"></span>
          </button>
        {/each}
      </div>
    </div>
  {/if}
</div>

// frontend/src/pages/settings/AgentColorPicker.tsx
import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { AGENT_COLORS, AGENT_COLOR_DEFAULT, getAgentColor } from "./agentColors";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { cn } from "@/lib/utils";

type AgentColorPickerProps = {
  value: string | null;
  onChange: (colorId: string | null) => void;
  disabled?: boolean;
};

export function AgentColorPicker({ value, onChange, disabled = false }: AgentColorPickerProps) {
  const [open, setOpen] = useState(false);
  const current = getAgentColor(value);
  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <button
          type="button"
          disabled={disabled}
          title={`Color: ${current.label}`}
          className={cn(
            "inline-flex h-9 items-center gap-1.5 rounded-md border border-input bg-muted/40 px-2 text-foreground transition-colors hover:bg-secondary/60",
            disabled && "cursor-not-allowed opacity-55",
          )}
        >
          <span className={cn("h-3.5 w-3.5 rounded-full", current.swatch)} />
          <ChevronDown className="h-3 w-3 opacity-60" />
        </button>
      </PopoverTrigger>
      <PopoverContent
        align="start"
        sideOffset={6}
        className="z-[1400] w-fit rounded-lg border border-border bg-popover p-2 shadow-xl"
      >
        <div className="grid grid-cols-6 gap-1">
          <button
            type="button"
            title={AGENT_COLOR_DEFAULT.label}
            onClick={() => {
              onChange(null);
              setOpen(false);
            }}
            className={cn(
              "inline-flex h-7 w-7 items-center justify-center rounded-md border border-transparent hover:bg-primary/10",
              value == null && "border-primary/60 bg-primary/15",
            )}
          >
            <span className={cn("h-4 w-4 rounded-full", AGENT_COLOR_DEFAULT.swatch)} />
          </button>
          {AGENT_COLORS.map(({ id, label, swatch }) => {
            const selected = value === id;
            return (
              <button
                key={id}
                type="button"
                title={label}
                onClick={() => {
                  onChange(id);
                  setOpen(false);
                }}
                className={cn(
                  "inline-flex h-7 w-7 items-center justify-center rounded-md border border-transparent hover:bg-primary/10",
                  selected && "border-primary/60 bg-primary/15",
                )}
              >
                <span className={cn("h-4 w-4 rounded-full", swatch)} />
              </button>
            );
          })}
        </div>
      </PopoverContent>
    </Popover>
  );
}
