// frontend3/src/pages/settings/ModelPricingEditor.svelte
<script lang="ts">
  import type { ModelCapabilityRow } from "../../../../backend/src/contracts/model-catalog";
  import { updateModelCapabilityOverride } from "@/api/client";
  import { createModelCapabilitiesQuery } from "@/hooks/queries/referenceData";
  import { queryKeys } from "@/hooks/queries/keys";
  import { queryClient } from "@/lib/queryClient";
  import { chatSearch } from "@/lib/router";
  import { ghostBtn } from "./settingsClasses";
  import {
    draftFromRow,
    formatCost,
    groupPricingRows,
    hasPricing,
    parseCostInput,
    pricingRowKey,
    sourceBadgeClass,
    type PricingEditState,
    type PricingRowState,
  } from "./modelPricingHelpers";

  const capabilitiesQuery = createModelCapabilitiesQuery();
  const rows = $derived(capabilitiesQuery.data?.models ?? []);
  const grouped = $derived(groupPricingRows(rows));

  const focusModels = $derived.by(() => {
    const raw = new URLSearchParams($chatSearch).get("focus");
    if (!raw) return new Set<string>();
    return new Set(
      raw
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean),
    );
  });

  let rowState = $state<Map<string, PricingRowState>>(new Map());
  let didScrollFocus = $state(false);

  function getRowState(row: ModelCapabilityRow): PricingRowState {
    return (
      rowState.get(pricingRowKey(row)) ?? {
        editing: false,
        draft: draftFromRow(row),
        saving: false,
        error: null,
      }
    );
  }

  function patchRowState(row: ModelCapabilityRow, patch: Partial<PricingRowState>): void {
    const key = pricingRowKey(row);
    const current = getRowState(row);
    const next = new Map(rowState);
    next.set(key, { ...current, ...patch });
    rowState = next;
  }

  function startEdit(row: ModelCapabilityRow): void {
    patchRowState(row, { editing: true, draft: draftFromRow(row), error: null });
  }

  function cancelEdit(row: ModelCapabilityRow): void {
    patchRowState(row, { editing: false, error: null });
  }

  function patchDraft(row: ModelCapabilityRow, patch: Partial<PricingEditState>): void {
    const state = getRowState(row);
    patchRowState(row, { draft: { ...state.draft, ...patch } });
  }

  async function saveRow(row: ModelCapabilityRow): Promise<void> {
    const state = getRowState(row);
    const selfHosted = state.draft.selfHosted;
    const inputCost = selfHosted ? null : parseCostInput(state.draft.input);
    const cachedCost = selfHosted ? null : parseCostInput(state.draft.cachedInput);
    const outputCost = selfHosted ? null : parseCostInput(state.draft.output);

    patchRowState(row, { saving: true, error: null });
    try {
      const result = await updateModelCapabilityOverride({
        provider_id: row.provider_id,
        model_name: row.model_name,
        input_cost_per_1m: inputCost,
        cached_input_cost_per_1m: cachedCost,
        output_cost_per_1m: outputCost,
        self_hosted: selfHosted,
        currency: "USD",
      });
      queryClient.setQueryData(queryKeys.modelCapabilities, { models: result.models });
      patchRowState(row, { editing: false, saving: false, error: null });
    } catch (e) {
      patchRowState(row, {
        saving: false,
        error: e instanceof Error ? e.message : String(e),
      });
    }
  }

  function scrollFocus(node: HTMLTableRowElement, focused: boolean): { destroy?: () => void } {
    if (focused && !didScrollFocus) {
      didScrollFocus = true;
      node.scrollIntoView({ behavior: "smooth", block: "center" });
    }
    return {};
  }
</script>

{#if capabilitiesQuery.isPending}
  <p class="text-sm text-muted-foreground">Loading model pricing…</p>
{:else if capabilitiesQuery.isError}
  <div class="rounded-[10px] border border-destructive/45 bg-destructive/10 px-3 py-2.5 text-[13px] text-destructive">
    {capabilitiesQuery.error instanceof Error ? capabilitiesQuery.error.message : String(capabilitiesQuery.error)}
  </div>
{:else if rows.length === 0}
  <div class="rounded-lg border border-dashed border-border bg-card p-[18px] text-muted-foreground">
    No models discovered yet. Connect a provider in <strong>Model Providers</strong> to populate this list.
  </div>
{:else}
  <div class="flex flex-col gap-4">
    <p class="text-[13px] text-muted-foreground">
      Override per-model pricing (USD per 1M tokens). Affects cost estimates in the chat UI.
    </p>
    {#each [...grouped.entries()] as [providerId, providerRows] (providerId)}
      <div class="rounded-lg border border-border bg-card">
        <div class="border-b border-border px-4 py-2.5 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
          {providerId}
        </div>
        <table class="w-full text-[13px]">
          <thead>
            <tr class="border-b border-border text-[11px] text-muted-foreground">
              <th class="px-4 py-2 text-left font-medium">Model</th>
              <th class="px-3 py-2 text-left font-medium">Source</th>
              <th class="px-3 py-2 text-center font-medium">Self-hosted</th>
              <th class="px-3 py-2 text-right font-medium">Input /1M</th>
              <th class="px-3 py-2 text-right font-medium">Cached /1M</th>
              <th class="px-3 py-2 text-right font-medium">Output /1M</th>
              <th class="px-3 py-2"></th>
            </tr>
          </thead>
          <tbody>
            {#each providerRows as row (row.model_name)}
              {@const state = getRowState(row)}
              {@const missing = !hasPricing(row) && !state.editing}
              {@const focused = focusModels.has(row.model_name)}
              <tr
                class="border-b border-border/50 last:border-0 {missing ? 'bg-amber-500/5' : ''} {focused
                  ? 'bg-primary/10 ring-1 ring-primary/30'
                  : ''}"
                use:scrollFocus={focused}
              >
                <td class="px-4 py-2.5 font-mono text-[12px]">
                  <span class={missing ? "text-amber-700 dark:text-amber-400" : ""}>{row.model_name}</span>
                </td>
                <td class="px-3 py-2.5">
                  <span class="rounded px-1.5 py-0.5 text-[10px] font-medium {sourceBadgeClass(row.source)}">
                    {row.source}
                  </span>
                </td>
                {#if state.editing}
                  <td class="px-3 py-2 text-center">
                    <input
                      type="checkbox"
                      checked={state.draft.selfHosted}
                      onchange={(e) => patchDraft(row, { selfHosted: e.currentTarget.checked })}
                      class="h-4 w-4 accent-primary"
                      title="Self-hosted (no per-token cost)"
                    />
                  </td>
                  <td class="px-3 py-2 text-right">
                    <input
                      type="text"
                      value={state.draft.selfHosted ? "" : state.draft.input}
                      disabled={state.draft.selfHosted}
                      oninput={(e) => patchDraft(row, { input: e.currentTarget.value })}
                      placeholder={state.draft.selfHosted ? "n/a" : "—"}
                      class="w-24 rounded border border-border bg-background px-2 py-1 font-mono text-xs disabled:opacity-50"
                    />
                  </td>
                  <td class="px-3 py-2 text-right">
                    <input
                      type="text"
                      value={state.draft.selfHosted ? "" : state.draft.cachedInput}
                      disabled={state.draft.selfHosted}
                      oninput={(e) => patchDraft(row, { cachedInput: e.currentTarget.value })}
                      placeholder={state.draft.selfHosted ? "n/a" : "—"}
                      class="w-24 rounded border border-border bg-background px-2 py-1 font-mono text-xs disabled:opacity-50"
                    />
                  </td>
                  <td class="px-3 py-2 text-right">
                    <input
                      type="text"
                      value={state.draft.selfHosted ? "" : state.draft.output}
                      disabled={state.draft.selfHosted}
                      oninput={(e) => patchDraft(row, { output: e.currentTarget.value })}
                      placeholder={state.draft.selfHosted ? "n/a" : "—"}
                      class="w-24 rounded border border-border bg-background px-2 py-1 font-mono text-xs disabled:opacity-50"
                    />
                  </td>
                  <td class="px-3 py-2.5">
                    <div class="flex items-center gap-1">
                      <button
                        type="button"
                        disabled={state.saving}
                        class={ghostBtn}
                        onclick={() => void saveRow(row)}
                      >
                        {state.saving ? "Saving…" : "Save"}
                      </button>
                      <button type="button" class="rounded p-1 text-muted-foreground hover:text-foreground" onclick={() => cancelEdit(row)}>
                        ✕
                      </button>
                    </div>
                    {#if state.error}
                      <div class="mt-1 text-[11px] text-destructive">{state.error}</div>
                    {/if}
                  </td>
                {:else}
                  <td class="px-3 py-2.5 text-center">
                    {#if row.self_hosted}
                      <span class="rounded bg-emerald-500/10 px-1.5 py-0.5 text-[10px] font-medium text-emerald-700 dark:text-emerald-400">
                        yes
                      </span>
                    {:else}
                      <span class="text-muted-foreground/50">—</span>
                    {/if}
                  </td>
                  <td class="px-3 py-2.5 text-right font-mono text-[12px]">
                    {#if row.self_hosted}
                      <span class="text-muted-foreground/50">n/a</span>
                    {:else if row.input_cost_per_1m == null}
                      <span class="text-amber-600 dark:text-amber-500">—</span>
                    {:else}
                      {formatCost(row.input_cost_per_1m)}
                    {/if}
                  </td>
                  <td class="px-3 py-2.5 text-right font-mono text-[12px]">
                    {#if row.self_hosted}
                      <span class="text-muted-foreground/50">n/a</span>
                    {:else if row.cached_input_cost_per_1m == null}
                      <span class="text-amber-600 dark:text-amber-500">—</span>
                    {:else}
                      {formatCost(row.cached_input_cost_per_1m)}
                    {/if}
                  </td>
                  <td class="px-3 py-2.5 text-right font-mono text-[12px]">
                    {#if row.self_hosted}
                      <span class="text-muted-foreground/50">n/a</span>
                    {:else if row.output_cost_per_1m == null}
                      <span class="text-amber-600 dark:text-amber-500">—</span>
                    {:else}
                      {formatCost(row.output_cost_per_1m)}
                    {/if}
                  </td>
                  <td class="px-3 py-2.5">
                    <button
                      type="button"
                      class="rounded p-1 text-muted-foreground hover:text-foreground"
                      title="Edit pricing"
                      onclick={() => startEdit(row)}
                    >
                      ✎
                    </button>
                  </td>
                {/if}
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    {/each}
  </div>
{/if}

// frontend/src/pages/settings/ModelPricingEditor.tsx
import { useMemo, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Pencil, Check, X, Server } from "lucide-react";
import type { ModelCapabilityRow } from "../../../../backend/src/contracts/model-catalog";
import { updateModelCapabilityOverride } from "../../api/client";
import { queryClient } from "@/lib/queryClient";
import { queryKeys } from "../../hooks/queries/keys";
import { useModelCapabilitiesQuery } from "../../hooks/queries/referenceData";
import { Spinner } from "../../components/ui/Spinner";
import { cn } from "@/lib/utils";
import { ghostBtn } from "./settingsClasses";

type EditState = {
  input: string;
  cachedInput: string;
  output: string;
  selfHosted: boolean;
};

type RowState = {
  editing: boolean;
  draft: EditState;
  saving: boolean;
  error: string | null;
};

function formatCost(value: number | null): string {
  if (value == null) return "—";
  return `$${value.toFixed(2)}`;
}

function parseCostInput(raw: string): number | null {
  const cleaned = raw.replace(/^\$/, "").trim();
  if (!cleaned) return null;
  const n = Number(cleaned);
  return Number.isFinite(n) && n >= 0 ? n : null;
}

function draftFromRow(row: ModelCapabilityRow): EditState {
  return {
    input: row.input_cost_per_1m != null ? String(row.input_cost_per_1m) : "",
    cachedInput: row.cached_input_cost_per_1m != null ? String(row.cached_input_cost_per_1m) : "",
    output: row.output_cost_per_1m != null ? String(row.output_cost_per_1m) : "",
    selfHosted: row.self_hosted === true,
  };
}

function hasPricing(row: ModelCapabilityRow): boolean {
  if (row.self_hosted) return true;
  return row.input_cost_per_1m != null && row.output_cost_per_1m != null;
}

function SourceBadge({ source }: { source: ModelCapabilityRow["source"] }) {
  const label = source === "override" ? "override" : source === "seed" ? "seed" : "discovered";
  const cls =
    source === "override"
      ? "bg-blue-500/10 text-blue-600 dark:text-blue-400"
      : source === "seed"
        ? "bg-muted text-muted-foreground"
        : "bg-muted text-muted-foreground";
  return (
    <span className={cn("rounded px-1.5 py-0.5 text-[10px] font-medium", cls)}>{label}</span>
  );
}

function CostCell({ value }: { value: number | null }) {
  if (value == null) {
    return <span className="text-amber-600 dark:text-amber-500">—</span>;
  }
  return <span>{formatCost(value)}</span>;
}

function PriceInput({
  label,
  value,
  onChange,
  disabled = false,
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  disabled?: boolean;
}) {
  return (
    <div className="flex flex-col gap-0.5">
      <label className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
        {label}
      </label>
      <input
        type="text"
        value={disabled ? "" : value}
        disabled={disabled}
        onChange={(e) => onChange(e.target.value)}
        placeholder={disabled ? "n/a" : "—"}
        className="w-24 rounded border border-border bg-background px-2 py-1 font-mono text-xs focus:outline-none focus:ring-1 focus:ring-primary disabled:cursor-not-allowed disabled:opacity-50"
      />
    </div>
  );
}

export function ModelPricingEditor() {
  const capabilitiesQuery = useModelCapabilitiesQuery();
  const rows = capabilitiesQuery.data?.models ?? [];
  const loading = capabilitiesQuery.isPending;
  const loadError = capabilitiesQuery.isError
    ? capabilitiesQuery.error instanceof Error
      ? capabilitiesQuery.error.message
      : String(capabilitiesQuery.error)
    : null;
  const [rowState, setRowState] = useState<Map<string, RowState>>(new Map());
  const [searchParams] = useSearchParams();
  const focusModels = useMemo(() => {
    const raw = searchParams.get("focus");
    if (!raw) return new Set<string>();
    return new Set(
      raw
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean),
    );
  }, [searchParams]);
  const firstFocusRowRef = useRef<HTMLTableRowElement | null>(null);
  const didScrollRef = useRef(false);

  function rowKey(row: ModelCapabilityRow) {
    return `${row.provider_id}::${row.model_name}`;
  }

  function getRowState(row: ModelCapabilityRow): RowState {
    return (
      rowState.get(rowKey(row)) ?? {
        editing: false,
        draft: draftFromRow(row),
        saving: false,
        error: null,
      }
    );
  }

  function patchRowState(row: ModelCapabilityRow, patch: Partial<RowState>) {
    setRowState((prev) => {
      const next = new Map(prev);
      const current = prev.get(rowKey(row)) ?? {
        editing: false,
        draft: draftFromRow(row),
        saving: false,
        error: null,
      };
      next.set(rowKey(row), { ...current, ...patch });
      return next;
    });
  }

  function startEdit(row: ModelCapabilityRow) {
    patchRowState(row, { editing: true, draft: draftFromRow(row), error: null });
  }

  function cancelEdit(row: ModelCapabilityRow) {
    patchRowState(row, { editing: false, error: null });
  }

  async function saveRow(row: ModelCapabilityRow) {
    const state = getRowState(row);
    const selfHosted = state.draft.selfHosted;
    const inputCost = selfHosted ? null : parseCostInput(state.draft.input);
    const cachedCost = selfHosted ? null : parseCostInput(state.draft.cachedInput);
    const outputCost = selfHosted ? null : parseCostInput(state.draft.output);

    patchRowState(row, { saving: true, error: null });
    try {
      const result = await updateModelCapabilityOverride({
        provider_id: row.provider_id,
        model_name: row.model_name,
        input_cost_per_1m: inputCost,
        cached_input_cost_per_1m: cachedCost,
        output_cost_per_1m: outputCost,
        self_hosted: selfHosted,
        currency: "USD",
      });
      queryClient.setQueryData(queryKeys.modelCapabilities, { models: result.models });
      patchRowState(row, { editing: false, saving: false, error: null });
    } catch (e) {
      patchRowState(row, { saving: false, error: e instanceof Error ? e.message : String(e) });
    }
  }

  const grouped = rows.reduce<Map<string, ModelCapabilityRow[]>>((acc, row) => {
    const group = acc.get(row.provider_id) ?? [];
    group.push(row);
    acc.set(row.provider_id, group);
    return acc;
  }, new Map());

  if (loading) {
    return (
      <div className="inline-flex items-center gap-2 text-muted-foreground">
        <Spinner size={16} />
        <span>Loading model pricing...</span>
      </div>
    );
  }

  if (loadError) {
    return (
      <div className="rounded-[10px] border border-destructive/45 bg-destructive/10 px-3 py-2.5 text-[13px] text-destructive">
        {loadError}
      </div>
    );
  }

  if (rows.length === 0) {
    return (
      <div className="rounded-lg border border-dashed border-border bg-card p-[18px] text-muted-foreground">
        No models discovered yet. Connect a provider in{" "}
        <strong>Model Providers</strong> to populate this list.
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-4">
      <p className="text-[13px] text-muted-foreground">
        Override per-model pricing (USD per 1M tokens). Affects cost estimates in the chat UI.
      </p>
      {Array.from(grouped.entries()).map(([providerId, providerRows]) => (
        <div key={providerId} className="rounded-lg border border-border bg-card">
          <div className="border-b border-border px-4 py-2.5 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            {providerId}
          </div>
          <table className="w-full text-[13px]">
            <thead>
              <tr className="border-b border-border text-[11px] text-muted-foreground">
                <th className="px-4 py-2 text-left font-medium">Model</th>
                <th className="px-3 py-2 text-left font-medium">Source</th>
                <th className="px-3 py-2 text-center font-medium">Self-hosted</th>
                <th className="px-3 py-2 text-right font-medium">Input /1M</th>
                <th className="px-3 py-2 text-right font-medium">Cached /1M</th>
                <th className="px-3 py-2 text-right font-medium">Output /1M</th>
                <th className="px-3 py-2" />
              </tr>
            </thead>
            <tbody>
              {providerRows.map((row) => {
                const state = getRowState(row);
                const missing = !hasPricing(row) && !state.editing;
                const focused = focusModels.has(row.model_name);
                const isFirstFocus =
                  focused && firstFocusRowRef.current === null && !didScrollRef.current;
                return (
                  <tr
                    key={row.model_name}
                    ref={(el) => {
                      if (isFirstFocus && el) {
                        firstFocusRowRef.current = el;
                        didScrollRef.current = true;
                        el.scrollIntoView({ behavior: "smooth", block: "center" });
                      }
                    }}
                    className={cn(
                      "border-b border-border/50 last:border-0",
                      missing && "bg-amber-500/5",
                      focused && "bg-primary/10 ring-1 ring-primary/30",
                    )}
                  >
                    <td className="px-4 py-2.5 font-mono text-[12px]">
                      <span className={missing ? "text-amber-700 dark:text-amber-400" : ""}>
                        {row.model_name}
                      </span>
                    </td>
                    <td className="px-3 py-2.5">
                      <SourceBadge source={row.source} />
                    </td>
                    {state.editing ? (
                      <>
                        <td className="px-3 py-2 text-center">
                          <input
                            type="checkbox"
                            checked={state.draft.selfHosted}
                            onChange={(e) =>
                              patchRowState(row, {
                                draft: { ...state.draft, selfHosted: e.target.checked },
                              })
                            }
                            className="h-4 w-4 cursor-pointer accent-primary"
                            title="Self-hosted (no per-token cost)"
                          />
                        </td>
                        <td className="px-3 py-2 text-right">
                          <PriceInput
                            label="input"
                            value={state.draft.input}
                            disabled={state.draft.selfHosted}
                            onChange={(v) =>
                              patchRowState(row, { draft: { ...state.draft, input: v } })
                            }
                          />
                        </td>
                        <td className="px-3 py-2 text-right">
                          <PriceInput
                            label="cached"
                            value={state.draft.cachedInput}
                            disabled={state.draft.selfHosted}
                            onChange={(v) =>
                              patchRowState(row, { draft: { ...state.draft, cachedInput: v } })
                            }
                          />
                        </td>
                        <td className="px-3 py-2 text-right">
                          <PriceInput
                            label="output"
                            value={state.draft.output}
                            disabled={state.draft.selfHosted}
                            onChange={(v) =>
                              patchRowState(row, { draft: { ...state.draft, output: v } })
                            }
                          />
                        </td>
                        <td className="px-3 py-2.5">
                          <div className="flex items-center gap-1">
                            <button
                              type="button"
                              disabled={state.saving}
                              onClick={() => void saveRow(row)}
                              className={cn(ghostBtn, "flex items-center gap-1 px-2 py-1 text-xs")}
                            >
                              <Check className="h-3 w-3" />
                              {state.saving ? "Saving…" : "Save"}
                            </button>
                            <button
                              type="button"
                              onClick={() => cancelEdit(row)}
                              className="rounded p-1 text-muted-foreground hover:text-foreground"
                            >
                              <X className="h-3.5 w-3.5" />
                            </button>
                          </div>
                          {state.error ? (
                            <div className="mt-1 text-[11px] text-destructive">{state.error}</div>
                          ) : null}
                        </td>
                      </>
                    ) : (
                      <>
                        <td className="px-3 py-2.5 text-center">
                          {row.self_hosted ? (
                            <span
                              className="inline-flex items-center gap-1 rounded bg-emerald-500/10 px-1.5 py-0.5 text-[10px] font-medium text-emerald-700 dark:text-emerald-400"
                              title="Self-hosted (no per-token cost)"
                            >
                              <Server className="h-3 w-3" />
                              yes
                            </span>
                          ) : (
                            <span className="text-muted-foreground/50">—</span>
                          )}
                        </td>
                        <td className="px-3 py-2.5 text-right font-mono text-[12px]">
                          {row.self_hosted ? (
                            <span className="text-muted-foreground/50">n/a</span>
                          ) : (
                            <CostCell value={row.input_cost_per_1m} />
                          )}
                        </td>
                        <td className="px-3 py-2.5 text-right font-mono text-[12px]">
                          {row.self_hosted ? (
                            <span className="text-muted-foreground/50">n/a</span>
                          ) : (
                            <CostCell value={row.cached_input_cost_per_1m} />
                          )}
                        </td>
                        <td className="px-3 py-2.5 text-right font-mono text-[12px]">
                          {row.self_hosted ? (
                            <span className="text-muted-foreground/50">n/a</span>
                          ) : (
                            <CostCell value={row.output_cost_per_1m} />
                          )}
                        </td>
                        <td className="px-3 py-2.5">
                          <button
                            type="button"
                            onClick={() => startEdit(row)}
                            className="rounded p-1 text-muted-foreground hover:text-foreground"
                            title="Edit pricing"
                          >
                            <Pencil className="h-3.5 w-3.5" />
                          </button>
                        </td>
                      </>
                    )}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      ))}
    </div>
  );
}
