// frontend/src/components/ui/AnchorTopScrollArea.tsx
import { useCallback, useEffect, useRef, useState, type ReactNode } from "react";

export type AnchorTopScrollAreaProps = {
  className?: string;
  topAnchorEntryId?: string | null;
  children: ReactNode;
};

type AnchorScrollInputs = {
  anchorTop: number;
  anchorBottom: number;
  totalContentHeight: number;
  viewportHeight: number;
};

type AnchorScrollPlan = {
  remainingContentHeight: number;
  spacerHeight: number;
  scrollTopTarget: number;
};

function calculateAnchorScrollPlan({
  anchorTop,
  anchorBottom,
  totalContentHeight,
  viewportHeight,
}: AnchorScrollInputs): AnchorScrollPlan {
  const remainingContentHeight = Math.max(0, totalContentHeight - anchorBottom);
  const anchorHeight = Math.max(0, anchorBottom - anchorTop);
  const visibleFromAnchorTop = anchorHeight + remainingContentHeight;
  const spacerHeight = Math.max(0, viewportHeight - visibleFromAnchorTop);
  // Single target formula for both branches.
  const scrollTopTarget = Math.max(0, anchorTop);
  return { remainingContentHeight, spacerHeight, scrollTopTarget };
}

export function AnchorTopScrollArea({ className, topAnchorEntryId = null, children }: AnchorTopScrollAreaProps) {
  const scrollRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const rafRef = useRef<number | null>(null);
  const triesRef = useRef(0);
  const lastAnchorIdRef = useRef<string | null>(null);
  const bottomSpacerRef = useRef(0);
  const [bottomSpacerPx, setBottomSpacerPx] = useState(0);

  useEffect(() => {
    bottomSpacerRef.current = bottomSpacerPx;
  }, [bottomSpacerPx]);

  const cancelAlignRaf = useCallback(() => {
    if (rafRef.current == null) return;
    cancelAnimationFrame(rafRef.current);
    rafRef.current = null;
  }, []);

  const getAnchor = useCallback((entryId: string): HTMLElement | null => {
    const contentEl = contentRef.current;
    if (!contentEl) return null;
    return contentEl.querySelector<HTMLElement>(`[data-chat-entry-id="${entryId}"]`);
  }, []);

  function offsetTopWithinAncestor(node: HTMLElement, ancestor: HTMLElement): number | null {
    let top = 0;
    let current: HTMLElement | null = node;
    while (current && current !== ancestor) {
      top += current.offsetTop;
      current = current.offsetParent as HTMLElement | null;
    }
    if (current !== ancestor) return null;
    return top;
  }

  const alignOnce = useCallback(
    (entryId: string): boolean => {
      const scrollEl = scrollRef.current;
      const contentEl = contentRef.current;
      const anchor = getAnchor(entryId);
      if (!scrollEl || !contentEl || !anchor) return false;

      const viewportHeight = scrollEl.clientHeight;
      const anchorTopFromOffsets = offsetTopWithinAncestor(anchor, contentEl);
      const anchorTop =
        anchorTopFromOffsets != null
          ? anchorTopFromOffsets
          : Math.max(
              0,
              scrollEl.scrollTop + (anchor.getBoundingClientRect().top - scrollEl.getBoundingClientRect().top),
            );
      const anchorBottom = anchorTop + anchor.offsetHeight;
      const totalContentHeight = Math.max(0, contentEl.scrollHeight);
      const plan = calculateAnchorScrollPlan({
        anchorTop,
        anchorBottom,
        totalContentHeight,
        viewportHeight,
      });

      if (Math.abs(plan.spacerHeight - bottomSpacerRef.current) > 1) {
        bottomSpacerRef.current = plan.spacerHeight;
        setBottomSpacerPx(plan.spacerHeight);
        return false;
      }
      scrollEl.scrollTop = Math.max(0, plan.scrollTopTarget);
      const deltaToTop = Math.abs(anchor.getBoundingClientRect().top - scrollEl.getBoundingClientRect().top);
      return deltaToTop <= 1;
    },
    [getAnchor],
  );

  const scheduleAlign = useCallback(
    (entryId: string) => {
      cancelAlignRaf();
      triesRef.current = 0;
      const run = () => {
        if (topAnchorEntryId !== entryId) return;
        const done = alignOnce(entryId);
        if (done) {
          rafRef.current = null;
          return;
        }
        triesRef.current += 1;
        if (triesRef.current > 30) {
          rafRef.current = null;
          return;
        }
        rafRef.current = requestAnimationFrame(run);
      };
      rafRef.current = requestAnimationFrame(run);
    },
    [alignOnce, cancelAlignRaf, topAnchorEntryId],
  );

  useEffect(() => {
    if (!topAnchorEntryId) {
      cancelAlignRaf();
      lastAnchorIdRef.current = null;
      bottomSpacerRef.current = 0;
      setBottomSpacerPx(0);
      return;
    }
    if (lastAnchorIdRef.current === topAnchorEntryId) return;
    lastAnchorIdRef.current = topAnchorEntryId;
    scheduleAlign(topAnchorEntryId);
    return cancelAlignRaf;
  }, [cancelAlignRaf, scheduleAlign, topAnchorEntryId]);

  return (
    <div ref={scrollRef} className={className}>
      <div ref={contentRef} className="relative flex min-h-full flex-col gap-0">
        {children}
      </div>
      <div aria-hidden className="shrink-0" style={{ height: `${bottomSpacerPx}px` }} />
    </div>
  );
}

// frontend3/src/components/ui/AnchorTopScrollArea.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import {
    calculateAnchorScrollPlan,
    offsetTopWithinAncestor,
    smoothScrollTo,
  } from "@/lib/anchorScroll";

  let {
    topAnchorEntryId = null,
    class: className = "",
    testId,
    children,
  }: {
    topAnchorEntryId?: string | null;
    class?: string;
    testId?: string;
    children: Snippet;
  } = $props();

  let scrollEl = $state<HTMLDivElement | null>(null);
  let contentEl = $state<HTMLDivElement | null>(null);
  let bottomSpacerPx = $state(0);
  let bottomSpacerRef = 0;
  let lastAnchorId: string | null = null;
  let rafRef: number | null = null;
  const animRafRef = { current: null as number | null };
  let tries = 0;

  function cancelAlignRaf(): void {
    if (rafRef != null) cancelAnimationFrame(rafRef);
    rafRef = null;
    if (animRafRef.current != null) cancelAnimationFrame(animRafRef.current);
    animRafRef.current = null;
  }

  function getAnchor(entryId: string): HTMLElement | null {
    if (!contentEl) return null;
    return contentEl.querySelector<HTMLElement>(`[data-chat-entry-id="${entryId}"]`);
  }

  function alignOnce(entryId: string): boolean {
    const scroll = scrollEl;
    const content = contentEl;
    const anchor = getAnchor(entryId);
    if (!scroll || !content || !anchor) return false;

    const viewportHeight = scroll.clientHeight;
    const anchorTopFromOffsets = offsetTopWithinAncestor(anchor, content);
    const anchorTop =
      anchorTopFromOffsets != null
        ? anchorTopFromOffsets
        : Math.max(
            0,
            scroll.scrollTop + (anchor.getBoundingClientRect().top - scroll.getBoundingClientRect().top),
          );
    const anchorBottom = anchorTop + anchor.offsetHeight;
    const plan = calculateAnchorScrollPlan({
      anchorTop,
      anchorBottom,
      totalContentHeight: Math.max(0, content.scrollHeight),
      viewportHeight,
    });

    if (Math.abs(plan.spacerHeight - bottomSpacerRef) > 1) {
      bottomSpacerRef = plan.spacerHeight;
      bottomSpacerPx = plan.spacerHeight;
      return false;
    }
    smoothScrollTo(scroll, Math.max(0, plan.scrollTopTarget), animRafRef);
    return true;
  }

  function scheduleAlign(entryId: string): void {
    cancelAlignRaf();
    tries = 0;
    const run = () => {
      if (topAnchorEntryId !== entryId) return;
      const done = alignOnce(entryId);
      if (done) {
        rafRef = null;
        return;
      }
      tries += 1;
      if (tries > 30) {
        rafRef = null;
        return;
      }
      rafRef = requestAnimationFrame(run);
    };
    rafRef = requestAnimationFrame(run);
  }

  $effect(() => {
    if (!topAnchorEntryId) {
      cancelAlignRaf();
      lastAnchorId = null;
      bottomSpacerRef = 0;
      bottomSpacerPx = 0;
      return;
    }
    if (lastAnchorId === topAnchorEntryId) return;
    lastAnchorId = topAnchorEntryId;
    scheduleAlign(topAnchorEntryId);
    return cancelAlignRaf;
  });
</script>

<div bind:this={scrollEl} class={className} data-testid={testId}>
  <div bind:this={contentEl} class="relative flex min-h-full flex-col gap-0">
    {@render children()}
  </div>
  <div aria-hidden="true" class="shrink-0" style="height: {bottomSpacerPx}px"></div>
</div>
