// frontend/src/pages/ChatPage.svelte
<script lang="ts">
  import ChatTranscript from "@/components/chat/ChatTranscript.svelte";
  import ChatComposer from "@/components/chat/ChatComposer.svelte";
  import ChatTitlePanel from "@/components/chat/ChatTitlePanel.svelte";
  import ConversationBranchesPanel from "@/components/chat/ConversationBranchesPanel.svelte";
  import ResizablePaneHandle from "@/components/ui/ResizablePaneHandle.svelte";
  import { isThoughtStreamEntry } from "@/protocol/chatEntry";
  import { createChatSessionState } from "@/lib/chatSessionState.svelte";
  import { setChatSessionContext } from "@/lib/chatSessionContext";
  import { resolveTopAnchorEntryId } from "@/lib/chatTopAnchor";
  import { agentIdFromSearch, chatSearch, navigate, settingsLinkFromSearch } from "@/lib/router";
  import { Pane, PaneGroup } from "paneforge";

  let {
    conversationId,
    search,
    sidebarVisible,
    onToggleSidebar,
    rightSidebarVisible,
    onToggleRightSidebar,
    settingsPressed,
  }: {
    conversationId: string | null;
    search: string;
    sidebarVisible: boolean;
    onToggleSidebar: () => void;
    rightSidebarVisible: boolean;
    onToggleRightSidebar: () => void;
    settingsPressed: boolean;
  } = $props();

  const session = createChatSessionState(() => conversationId);

  let selectedBranchAnchorEntryId = $state<string | null>(null);
  let composerTextareaRef = $state<HTMLTextAreaElement | null>(null);
  const selectedAgentId = $derived(agentIdFromSearch(search));
  setChatSessionContext({
    getConversationId: () => conversationId,
    getActivePathEntries: () => session.activePathEntries,
    setActiveLeaf: (entryId) => session.setActiveLeaf(entryId),
    switchToBranch: (branchEntryId) => session.switchToBranch(branchEntryId),
    siblingsOf: (entryId) => session.store.siblingsOf(entryId),
  });

  const activePathEntries = $derived(session.activePathEntries.map((row$) => row$.get()));
  const activePathEntryById = $derived(new Map(activePathEntries.map((entry) => [entry.id, entry])));
  const tripletStreamIdByThoughtId = $derived.by(() => {
    const map = new Map<string, string>();
    for (const entry of activePathEntries) {
      if (isThoughtStreamEntry(entry)) map.set(entry.thoughtId, entry.id);
    }
    return map;
  });

  function resolveVisibleAnchorEntryId(entryId: string): string {
    const selected = activePathEntryById.get(entryId);
    if (!selected) return entryId;
    if (selected.type !== "thought-prepare" && selected.type !== "thought-action") return entryId;
    return tripletStreamIdByThoughtId.get(selected.thoughtId) ?? entryId;
  }

  const topAnchorEntryId = $derived(
    resolveTopAnchorEntryId(conversationId, session.activePathEntries, selectedBranchAnchorEntryId),
  );

  function handleSent(_optimisticRowId: string): void {
    selectedBranchAnchorEntryId = null;
  }

  function openSettings(): void {
    navigate(settingsLinkFromSearch($chatSearch));
  }

  let lastConversationId = $state<string | null | undefined>(undefined);
  $effect(() => {
    const id = conversationId;
    if (id === lastConversationId) return;
    lastConversationId = id;
    selectedBranchAnchorEntryId = null;
  });

  $effect(() => {
    const id = requestAnimationFrame(() => composerTextareaRef?.focus());
    return () => cancelAnimationFrame(id);
  });

</script>

<div class="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">
  <ChatTitlePanel
    {conversationId}
    {sidebarVisible}
    {onToggleSidebar}
    {rightSidebarVisible}
    {onToggleRightSidebar}
    onOpenSettings={openSettings}
    {settingsPressed}
  />
  {#if rightSidebarVisible}
    <PaneGroup direction="horizontal" autoSaveId="chat-right-branches-layout" class="min-h-0 min-w-0 flex-1">
      <Pane minSize={30} class="flex min-h-0 min-w-0 flex-col overflow-hidden">
        <ChatTranscript
          {conversationId}
          entries={session.activePathEntries}
          isSessionLoading={session.isSessionLoading}
          {selectedAgentId}
          {topAnchorEntryId}
        />
        <ChatComposer
          {conversationId}
          {search}
          pendingMessages={session.pendingMessages}
          appendOptimisticUserMessage={session.appendOptimisticUserMessage}
          onSent={handleSent}
          bind:textareaRef={composerTextareaRef}
        />
      </Pane>
      <ResizablePaneHandle withHandle />
      <Pane defaultSize={26} minSize={16} maxSize={45} class="min-h-0 min-w-0 overflow-hidden">
        <aside class="h-full min-h-0 overflow-y-auto border-l border-border bg-sidebar">
          <ConversationBranchesPanel
            {conversationId}
            allEntries={session.allEntries}
            activePathEntries={session.activePathEntries}
            switchToBranch={session.switchToBranch}
            onAnchorEntrySelected={(entryId) => {
              selectedBranchAnchorEntryId = resolveVisibleAnchorEntryId(entryId);
            }}
          />
        </aside>
      </Pane>
    </PaneGroup>
  {:else}
    <div class="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">
      <ChatTranscript
        {conversationId}
        entries={session.activePathEntries}
        isSessionLoading={session.isSessionLoading}
        {selectedAgentId}
        {topAnchorEntryId}
      />
      <ChatComposer
        {conversationId}
        {search}
        pendingMessages={session.pendingMessages}
        appendOptimisticUserMessage={session.appendOptimisticUserMessage}
        onSent={handleSent}
        bind:textareaRef={composerTextareaRef}
      />
    </div>
  {/if}
</div>

// frontend/src/pages/ChatPage.tsx
import { memo, useCallback, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import {
  agentIdFromSearchParams,
  type ChatAgentSelection,
} from "../components/chat/ChatAgentToolbar";
import { ChatTitlePanel } from "../components/chat/header/ChatTitlePanel";
import { ConversationBranchesPanel } from "../components/chat/ConversationBranchesPanel";
import { TerminalPanel } from "../components/terminal/TerminalPanel";
import { ChatComposer } from "../components/chat/ChatComposer";
import { type SelectedAttachment } from "../components/chat/AttachmentChips";
import type { ThoughtTripletRefs } from "../components/chat/ChatMessageRow";
import { ChatTranscriptPane } from "../components/chat/ChatTranscriptPane";
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "../components/ui/resizable";
import { ChatSessionContext, useThoughtExpandedStageState } from "../hooks/chatSessionContext";
import { useChatSession } from "../hooks/useChatSession";
import { useFocusOnFirstFrame } from "../hooks/useFocusOnFirstFrame";
import { useTasks } from "../hooks/useTasks";
import { isThoughtStreamEntry } from "../protocol/chatEntry";

type ChatPageProps = {
  conversationId: string | null;
  sidebarVisible: boolean;
  onToggleSidebar: () => void;
  rightSidebarVisible: boolean;
  onToggleRightSidebar: () => void;
  terminalVisible: boolean;
  onToggleTerminal: () => void;
  onOpenSettings: () => void;
  settingsPressed?: boolean;
};

const ChatPage = memo(function ChatPage({
  conversationId,
  sidebarVisible,
  onToggleSidebar,
  rightSidebarVisible,
  onToggleRightSidebar,
  terminalVisible,
  onToggleTerminal,
  onOpenSettings,
  settingsPressed = false,
}: ChatPageProps) {
  const composerTextareaRef = useFocusOnFirstFrame<HTMLTextAreaElement>();
  const [searchParams] = useSearchParams();
  const [input, setInput] = useState("");
  const [selectedFiles, setSelectedFiles] = useState<SelectedAttachment[]>([]);
  const [previewUrls, setPreviewUrls] = useState<string[]>([]);
  const [topAnchorEntryId, setTopAnchorEntryId] = useState<string | null>(null);
  const [selectedBranchAnchorEntryId, setSelectedBranchAnchorEntryId] = useState<string | null>(null);
  const [agentSelection, setAgentSelection] = useState<ChatAgentSelection>(() => ({
    agentId: agentIdFromSearchParams(searchParams) || "",
    llm: null,
    modelPresetId: null,
  }));

  const onAgentSelectionChange = useCallback((selection: ChatAgentSelection) => {
    setAgentSelection(selection);
  }, []);

  const {
    sessionStore,
    activePathEntries: chatEntries,
    allEntries,
    pendingMessages,
    isSessionLoading,
    setActiveLeaf,
    switchToBranch,
    appendOptimisticUserMessage,
  } = useChatSession(conversationId);
  const { tasks } = useTasks();
  const agentRunning = useMemo(
    () =>
      Boolean(
        conversationId &&
          tasks.some((task) => task.conversationId === conversationId && task.status === "running"),
      ),
    [conversationId, tasks],
  );
  const { expandedStageBySlotKey, setSlotExpandedStage, resetExpandedStages } = useThoughtExpandedStageState();
  const chatSessionContextValue = useMemo(
    () => ({
      conversationId,
      sessionStore,
      activePathEntries: chatEntries,
      allEntries,
      setActiveLeaf,
      switchToBranch,
      expandedStageBySlotKey,
      setSlotExpandedStage,
    }),
    [conversationId, sessionStore, chatEntries, allEntries, setActiveLeaf, switchToBranch, expandedStageBySlotKey, setSlotExpandedStage],
  );
  const activePathEntries = chatEntries.map((entry$) => entry$.get());
  const activePathEntryById = useMemo(() => new Map(activePathEntries.map((entry) => [entry.id, entry])), [activePathEntries]);
  const tripletStreamIdByThoughtId = useMemo(() => {
    const map = new Map<string, string>();
    for (const entry of activePathEntries) {
      if (isThoughtStreamEntry(entry)) {
        map.set(entry.thoughtId, entry.id);
      }
    }
    return map;
  }, [activePathEntries]);
  const thoughtTripletsById = useMemo(() => {
    const map = new Map<string, ThoughtTripletRefs>();
    for (const entry$ of chatEntries) {
      const entry = entry$.get();
      if (isThoughtStreamEntry(entry)) {
        const current = map.get(entry.thoughtId) ?? {};
        current.streamEntry$ = entry$;
        map.set(entry.thoughtId, current);
      } else if (entry.type === "thought-action") {
        const current = map.get(entry.thoughtId) ?? {};
        current.actionEntry = entry;
        map.set(entry.thoughtId, current);
      }
    }
    return map;
  }, [chatEntries]);
  const visibleEntries = useMemo(
    () =>
      chatEntries.filter((entry$) => {
        const entry = entry$.get();
        return !isThoughtStreamEntry(entry) && entry.type !== "thought-action";
      }),
    [chatEntries],
  );
  const resolveVisibleAnchorEntryId = useCallback(
    (entryId: string): string => {
      const selected = activePathEntryById.get(entryId);
      if (!selected) return entryId;
      if (selected.type !== "thought-prepare" && selected.type !== "thought-action") {
        return entryId;
      }
      return tripletStreamIdByThoughtId.get(selected.thoughtId) ?? entryId;
    },
    [activePathEntryById, tripletStreamIdByThoughtId],
  );
  const canSend = input.trim().length > 0 || selectedFiles.length > 0;

  useEffect(() => {
    setInput("");
    setSelectedFiles([]);
    setTopAnchorEntryId(null);
    setSelectedBranchAnchorEntryId(null);
    resetExpandedStages();
  }, [conversationId, resetExpandedStages]);

  useEffect(() => {
    const id = requestAnimationFrame(() => composerTextareaRef.current?.focus());
    return () => cancelAnimationFrame(id);
  }, [conversationId, composerTextareaRef]);

  useEffect(() => {
    const urls = selectedFiles.map(({ file }) =>
      file.type.startsWith("image/") || file.type === "application/pdf" ? URL.createObjectURL(file) : "",
    );
    setPreviewUrls(urls);
    return () => {
      urls.forEach((url) => {
        if (url) URL.revokeObjectURL(url);
      });
    };
  }, [selectedFiles]);

  useEffect(() => {
    if (!conversationId || chatEntries.length === 0) {
      setTopAnchorEntryId(null);
      setSelectedBranchAnchorEntryId(null);
      return;
    }
    if (selectedBranchAnchorEntryId) {
      const existsInActivePath = chatEntries.some((row$) => row$.id === selectedBranchAnchorEntryId);
      if (existsInActivePath) {
        setTopAnchorEntryId(selectedBranchAnchorEntryId);
        return;
      }
      setSelectedBranchAnchorEntryId(null);
    }
    for (let i = chatEntries.length - 1; i >= 0; i -= 1) {
      const row = chatEntries[i].get();
      if (row.type === "user-message") {
        setTopAnchorEntryId(row.id);
        return;
      }
    }
    setTopAnchorEntryId(null);
  }, [conversationId, chatEntries, selectedBranchAnchorEntryId]);

  const handleSent = useCallback((optimisticRowId: string) => {
    setSelectedBranchAnchorEntryId(null);
    setTopAnchorEntryId(optimisticRowId);
  }, []);

  const chatPane = (
    <div className="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">
      <main className="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">
        <ChatTranscriptPane
          conversationId={conversationId}
          visibleEntries={visibleEntries}
          thoughtTripletsById={thoughtTripletsById}
          isSessionLoading={isSessionLoading}
          selectedAgentId={agentSelection.agentId}
          topAnchorEntryId={topAnchorEntryId}
        />
      </main>
      <ChatComposer
        conversationId={conversationId}
        composerTextareaRef={composerTextareaRef}
        input={input}
        setInput={setInput}
        selectedFiles={selectedFiles}
        setSelectedFiles={setSelectedFiles}
        previewUrls={previewUrls}
        agentSelection={agentSelection}
        onAgentSelectionChange={onAgentSelectionChange}
        canSend={canSend}
        appendOptimisticUserMessage={appendOptimisticUserMessage}
        onSent={handleSent}
        agentRunning={agentRunning}
        pendingMessages={pendingMessages}
      />
    </div>
  );

  const chatAndTerminal = terminalVisible ? (
    <ResizablePanelGroup direction="vertical" autoSaveId="chat-terminal-layout" className="min-h-0 min-w-0 flex-1">
      <ResizablePanel minSize={20} className="flex min-h-0 min-w-0 flex-col overflow-hidden">
        {chatPane}
      </ResizablePanel>
      <ResizableHandle withHandle />
      <ResizablePanel defaultSize={30} minSize={15} maxSize={70} className="min-h-0 min-w-0 overflow-hidden border-t border-border">
        <TerminalPanel className="h-full w-full" />
      </ResizablePanel>
    </ResizablePanelGroup>
  ) : chatPane;

  return (
    <ChatSessionContext.Provider value={chatSessionContextValue}>
    <div className="flex min-h-0 flex-1 flex-col overflow-hidden">
      <ChatTitlePanel
        conversationId={conversationId}
        sidebarVisible={sidebarVisible}
        onToggleSidebar={onToggleSidebar}
        rightSidebarVisible={rightSidebarVisible}
        onToggleRightSidebar={onToggleRightSidebar}
        terminalVisible={terminalVisible}
        onToggleTerminal={onToggleTerminal}
        onOpenSettings={onOpenSettings}
        settingsPressed={settingsPressed}
      />
      {rightSidebarVisible ? (
        <ResizablePanelGroup direction="horizontal" autoSaveId="chat-right-branches-layout" className="min-h-0 min-w-0 flex-1">
          <ResizablePanel minSize={30} className="flex min-h-0 min-w-0 flex-col overflow-hidden">
            {chatAndTerminal}
          </ResizablePanel>
          <ResizableHandle withHandle />
          <ResizablePanel defaultSize={26} minSize={16} maxSize={45} className="min-h-0 min-w-0 overflow-hidden">
            <aside className="min-h-0 min-w-0 h-full overflow-y-auto border-l border-border bg-sidebar">
              <ConversationBranchesPanel
                onAnchorEntrySelected={(entryId) => {
                  const visibleAnchorId = resolveVisibleAnchorEntryId(entryId);
                  setSelectedBranchAnchorEntryId(visibleAnchorId);
                  setTopAnchorEntryId(visibleAnchorId);
                }}
              />
            </aside>
          </ResizablePanel>
        </ResizablePanelGroup>
      ) : (
        <div className="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden">
          {chatAndTerminal}
        </div>
      )}
    </div>
    </ChatSessionContext.Provider>
  );
});

export { ChatPage };
