// frontend/src/pages/SettingsPage.tsx
import { useEffect, useMemo, useState } from "react";
import { useLocation, useNavigate, useParams, useSearchParams } from "react-router-dom";
import type { AgentListItemResponse } from "../../../backend/src/contracts/agents";
import type { LlmProviderSettingsDocument } from "../../../backend/src/contracts/settings";
import type { ModelPresetResponse } from "../../../backend/src/contracts/model-presets";
import {
  createAgent as createAgentApi,
  createModelPreset,
  deleteAgentById,
  setDefaultAgent,
  deleteModelPresetById,
  getAgentById,
  getLlmProviderSettings,
  getTools as getToolsApi,
  getModelPresetById,
  testLlmProviderConnection,
  updateAgentById,
  updateModelPresetById,
  updateLlmProviderSettings,
} from "../api/client";
import { AsyncButton } from "../components/ui/AsyncButton";
import { Spinner } from "../components/ui/Spinner";
import { cn } from "@/lib/utils";
import { AgentsEditor } from "./settings/AgentsEditor";
import { GlobalModelSettingsCard } from "./settings/GlobalModelSettingsCard";
import { ModelPresetsEditor } from "./settings/ModelPresetsEditor";
import { ModelPricingEditor } from "./settings/ModelPricingEditor";
import { filterProviders, parseSettingsSection, buildModelGroups } from "./settings/helpers";
import type { LlmSettings } from "../types/llmSettings";
import { useLlmSettings } from "../hooks/llmSettingsContext";
import { refreshAgents, refreshModelPresets } from "../hooks/queries/invalidate";
import { useAgentsQuery, useModelPresetsQuery } from "../hooks/queries/referenceData";
import { ProviderCard } from "./settings/ProviderCard";
import { SettingsHeader } from "./settings/SettingsHeader";
import { SettingsSidebar } from "./settings/SettingsSidebar";
import { ghostBtn, settingsPlaceholderBox } from "./settings/settingsClasses";
import { notifyToast } from "../utils/toast";

function ToolsSettingsPlaceholder() {
  return (
    <div className={settingsPlaceholderBox}>
      Per-agent tool enablement and approval policy: open <strong>Agents</strong> → pick an agent →{" "}
      <strong>Tools &amp; permissions</strong>.
    </div>
  );
}

export function SettingsPage() {
  const { setProviders: setGlobalProviders } = useLlmSettings();
  const [settings, setSettings] = useState<LlmSettings | null>(null);
  const [loadingSettings, setLoadingSettings] = useState(true);
  const [search, setSearch] = useState("");
  const [modelFilters, setModelFilters] = useState<Record<string, string>>({});
  const [collapsedModels, setCollapsedModels] = useState<Record<string, boolean>>({});
  const [searchParams, setSearchParams] = useSearchParams();

  const agentEditId = searchParams.get("agent")?.trim() || "";
  function setAgentEditId(nextId: string) {
    const t = nextId.trim();
    setSearchParams(
      (prev) => {
        const n = new URLSearchParams(prev);
        if (!t) n.delete("agent");
        else n.set("agent", t);
        return n;
      },
      { replace: true },
    );
  }

  const { data: agents = [] } = useAgentsQuery();
  const [currentAgent, setCurrentAgent] = useState<AgentListItemResponse | null>(null);
  const [agentLoading, setAgentLoading] = useState(false);
  const [agentLoadError, setAgentLoadError] = useState<string | null>(null);
  const presetEditIdRaw = searchParams.get("preset")?.trim() || "";
  const presetEditId = /^\d+$/.test(presetEditIdRaw) ? Number(presetEditIdRaw) : null;
  function setPresetEditId(nextId: number | null) {
    setSearchParams(
      (prev) => {
        const n = new URLSearchParams(prev);
        if (nextId == null) n.delete("preset");
        else n.set("preset", String(nextId));
        return n;
      },
      { replace: true },
    );
  }
  const { data: presets = [] } = useModelPresetsQuery();
  const [toolCatalog, setToolCatalog] = useState<Record<string, unknown>[]>([]);
  const [currentPreset, setCurrentPreset] = useState<ModelPresetResponse | null>(null);
  const [presetLoading, setPresetLoading] = useState(false);
  const [presetLoadError, setPresetLoadError] = useState<string | null>(null);

  const { section } = useParams();
  const navigate = useNavigate();
  const location = useLocation();
  const activeSection = parseSettingsSection(section);

  async function load() {
    setLoadingSettings(true);
    try {
      const data = (await getLlmProviderSettings()) as LlmSettings;
      setSettings(data);
      return true;
    } finally {
      setLoadingSettings(false);
    }
  }

  async function save() {
    if (!settings) return false;
    await updateLlmProviderSettings(settings as unknown as LlmProviderSettingsDocument);
    // Push the just-persisted providers straight into the global store so
    // model selectors elsewhere (e.g. the prepare-step editor) update without
    // a reload — no server round-trip, we already hold the saved data.
    setGlobalProviders(settings.providers ?? []);
    return true;
  }

  async function testConnection(provider: LlmSettings["providers"][number]) {
    const res = await testLlmProviderConnection({
      provider_id: String(provider.id || ""),
      settings: provider.settings || {},
    });
    if (!res?.ok) throw new Error(res?.detail || "Connection test failed");
    const fetchedModels = Array.isArray(res?.models) ? res.models : [];
    setSettings((prev) => {
      if (!prev?.providers) return prev;
      const next = structuredClone(prev);
      const idx = next.providers.findIndex((x) => x?.id === provider?.id);
      if (idx >= 0) {
        const p = next.providers[idx] as Record<string, unknown>;
        p.models = fetchedModels;
        p.models_verified = true;
      }
      return next;
    });
    return true;
  }

  useEffect(() => {
    void load();
  }, []);

  async function loadAgent(aid: string) {
    setAgentLoading(true);
    setAgentLoadError(null);
    setCurrentAgent(null);
    try {
      const ag = await getAgentById(aid);
      setCurrentAgent(ag);
    } catch (e) {
      setAgentLoadError(e instanceof Error ? e.message : String(e));
    } finally {
      setAgentLoading(false);
    }
  }

  async function saveAgent() {
    if (!currentAgent) throw new Error("No agent loaded");
    const saved = await updateAgentById(currentAgent.id, {
      name: currentAgent.name,
      system_prompt: currentAgent.system_prompt,
      default_llm_configuration: currentAgent.default_llm_configuration,
      default_model_preset_id: currentAgent.default_model_preset_id,
      icon: currentAgent.icon,
      color: currentAgent.color,
    });
    setCurrentAgent(saved);
    await refreshAgents();
    return true;
  }

  async function saveAgentAndOpenChat(targetId?: string) {
    if (!currentAgent) throw new Error("No agent loaded");
    await saveAgent();
    const id = targetId || currentAgent.id;
    navigate(`/chat/new?agent=${encodeURIComponent(id)}`);
    return true;
  }

  async function createAgent() {
    const created = await createAgentApi();
    await refreshAgents();
    setAgentEditId(created.id);
    await loadAgent(created.id);
    notifyToast({ message: "Agent created", type: "success", durationMs: 4000 });
  }

  async function setLoadedAgentAsDefault() {
    if (!currentAgent) return;
    const updated = await setDefaultAgent(currentAgent.id);
    setCurrentAgent(updated);
    await refreshAgents();
  }

  async function deleteLoadedAgent() {
    if (!currentAgent) return;
    await deleteAgentById(currentAgent.id);
    const remaining = await refreshAgents();
    if (remaining.length > 0) {
      setAgentEditId(remaining[0].id);
      await loadAgent(remaining[0].id);
    } else {
      setAgentEditId("");
      setCurrentAgent(null);
    }
    notifyToast({ message: "Agent deleted", type: "success", durationMs: 4000 });
  }

  async function loadToolCatalog(): Promise<Record<string, unknown>[]> {
    try {
      const rows = await getToolsApi();
      const out = Array.isArray(rows)
        ? ((rows as unknown[]).filter((x) => x && typeof x === "object" && !Array.isArray(x)) as Record<
            string,
            unknown
          >[])
        : [];
      setToolCatalog(out);
      return out;
    } catch {
      setToolCatalog([]);
      return [];
    }
  }

  async function loadPreset(id: number) {
    setPresetLoading(true);
    setPresetLoadError(null);
    setCurrentPreset(null);
    try {
      const row = await getModelPresetById(id);
      setCurrentPreset(row);
    } catch (e) {
      setPresetLoadError(e instanceof Error ? e.message : String(e));
    } finally {
      setPresetLoading(false);
    }
  }

  async function savePreset() {
    if (!currentPreset) throw new Error("No preset loaded");
    const saved = await updateModelPresetById(currentPreset.id, {
      name: currentPreset.name,
      parameters: currentPreset.parameters,
    });
    setCurrentPreset(saved);
    await refreshModelPresets();
    return true;
  }

  async function createPreset() {
    const created = await createModelPreset({});
    await refreshModelPresets();
    setPresetEditId(created.id);
    await loadPreset(created.id);
    notifyToast({ message: "Model preset created", type: "success", durationMs: 4000 });
  }

  async function deleteLoadedPreset() {
    if (!currentPreset) return;
    await deleteModelPresetById(currentPreset.id);
    const remaining = await refreshModelPresets();
    if (remaining.length > 0) {
      setPresetEditId(remaining[0].id);
      await loadPreset(remaining[0].id);
    } else {
      setPresetEditId(null);
      setCurrentPreset(null);
    }
    notifyToast({ message: "Model preset deleted", type: "success", durationMs: 4000 });
  }

  useEffect(() => {
    if (activeSection !== "agents") return;
    void loadToolCatalog().then(() => {
      if (agents.length === 0) return;
      if (agentEditId && agents.some((a) => a.id === agentEditId)) return;
      setAgentEditId(agents[0].id);
    });
  }, [activeSection, agents, agentEditId]);

  useEffect(() => {
    if (activeSection === "agents" && agentEditId) {
      void loadAgent(agentEditId);
    }
  }, [activeSection, agentEditId]);

  useEffect(() => {
    if (activeSection !== "model-presets") return;
    if (presets.length === 0) return;
    if (presetEditId != null && presets.some((p) => p.id === presetEditId)) return;
    setPresetEditId(presets[0].id);
  }, [activeSection, presets, presetEditId]);

  useEffect(() => {
    if (activeSection === "model-presets" && presetEditId != null) {
      void loadPreset(presetEditId);
    }
  }, [activeSection, presetEditId]);

  const modelGroups = useMemo(
    () => (settings ? buildModelGroups(settings.providers) : []),
    [settings],
  );
  const providerCards = useMemo(
    () => filterProviders(settings?.providers, search),
    [settings, search],
  );

  if (loadingSettings) {
    return (
      <section className="flex flex-col gap-3 p-4">
        <div className="inline-flex items-center gap-2 text-muted-foreground">
          <Spinner size={16} />
          <span>Loading settings...</span>
        </div>
      </section>
    );
  }

  if (!settings) {
    return <section className="p-4">Failed to load settings.</section>;
  }

  return (
    <section className="min-h-0 w-full flex-1 overflow-auto">
      <div className="grid grid-cols-1 gap-4 p-4 md:grid-cols-[280px_minmax(0,1fr)]">
        <SettingsSidebar activeSection={activeSection} navigate={navigate} settingsSearch={location.search} />

        <main className="flex min-w-0 flex-col gap-3.5">
          {activeSection === "model-providers" ||
          activeSection === "model-presets" ||
          activeSection === "model-pricing" ||
          activeSection === "agents" ? null : (
            <SettingsHeader activeSection={activeSection} search={search} setSearch={setSearch} />
          )}

          {activeSection === "model-providers" ? (
            <div className="flex flex-col gap-3">
              <GlobalModelSettingsCard settings={settings} setSettings={setSettings} modelGroups={modelGroups} />
              {providerCards.map((p) => (
                <ProviderCard
                  key={String(p.id)}
                  provider={p}
                  settings={settings}
                  setSettings={setSettings}
                  testConnection={testConnection}
                  modelFilters={modelFilters}
                  setModelFilters={setModelFilters}
                  collapsedModels={collapsedModels}
                  setCollapsedModels={setCollapsedModels}
                />
              ))}
            </div>
          ) : activeSection === "model-presets" ? (
            <ModelPresetsEditor
              presets={presets}
              presetEditId={presetEditId}
              setPresetEditId={(id) => setPresetEditId(id)}
              currentPreset={currentPreset}
              setCurrentPreset={setCurrentPreset}
              loading={presetLoading}
              loadError={presetLoadError}
              createPreset={createPreset}
              savePreset={savePreset}
              deletePreset={deleteLoadedPreset}
            />
          ) : activeSection === "agents" ? (
            <AgentsEditor
              agents={agents}
              presets={presets}
              toolCatalog={toolCatalog}
              agentEditId={agentEditId}
              setAgentEditId={setAgentEditId}
              currentAgent={currentAgent}
              setCurrentAgent={setCurrentAgent}
              saveAgent={saveAgent}
              saveAgentAndOpenChat={saveAgentAndOpenChat}
              createAgent={createAgent}
              deleteLoadedAgent={deleteLoadedAgent}
              setLoadedAgentAsDefault={setLoadedAgentAsDefault}
              agentLoadError={agentLoadError}
              agentLoading={agentLoading}
              modelGroups={modelGroups}
            />
          ) : activeSection === "model-pricing" ? (
            <ModelPricingEditor />
          ) : activeSection === "tools" ? (
            <ToolsSettingsPlaceholder />
          ) : (
            <div className={settingsPlaceholderBox}>Skills UI placeholder.</div>
          )}

          {activeSection === "model-providers" ? (
            <div className="flex items-center gap-2.5">
              <AsyncButton onClickAsync={save} className={cn(ghostBtn, "border-slate-300")}>
                Save
              </AsyncButton>
            </div>
          ) : null}
        </main>
      </div>
    </section>
  );
}

// frontend/src/pages/SettingsPage.svelte
<script lang="ts">
  import SettingsSidebar from "./settings/SettingsSidebar.svelte";
  import SettingsSectionView from "./settings/SettingsSectionView.svelte";
  import { parseSettingsSection, type SettingsSection } from "./settings/helpers";
  import { chatSearch, navigate } from "@/lib/router";
  import {
    createAgent as createAgentApi,
    createModelPreset,
    deleteAgentById,
    deleteModelPresetById,
    getAgentById,
    getLlmProviderSettings,
    getModelPresetById,
    getTools,
    setDefaultAgent,
    testLlmProviderConnection,
    updateAgentById,
    updateLlmProviderSettings,
    updateModelPresetById,
  } from "@/api/client";
  import type { AgentListItemResponse } from "../../../backend/src/contracts/agents";
  import type { ModelPresetResponse } from "../../../backend/src/contracts/model-presets";
  import type { LlmProviderSettingsDocument } from "../../../backend/src/contracts/settings";
  import { createAgentsQuery, createModelPresetsQuery } from "@/hooks/queries/referenceData";
  import { queryKeys } from "@/hooks/queries/keys";
  import { queryClient } from "@/lib/queryClient";
  import type { LlmSettings } from "@/types/llmSettings";
  import { notifyError, notifySuccess } from "@/utils/toast";

  let { sectionRaw }: { sectionRaw: string | undefined } = $props();

  const activeSection = $derived(parseSettingsSection(sectionRaw));
  const agentsQuery = createAgentsQuery();
  const presetsQuery = createModelPresetsQuery();

  let settings = $state<LlmSettings | null>(null);
  let settingsLoading = $state(true);
  let providerSearch = $state("");
  let modelFilters = $state<Record<string, string>>({});
  let collapsedModels = $state<Record<string, boolean>>({});

  let agentEditId = $state("");
  let currentAgent = $state<AgentListItemResponse | null>(null);
  let agentLoading = $state(false);
  let agentLoadError = $state<string | null>(null);
  let toolCatalog = $state<Record<string, unknown>[]>([]);

  let presetEditId = $state<number | null>(null);
  let currentPreset = $state<ModelPresetResponse | null>(null);
  let presetLoading = $state(false);
  let presetLoadError = $state<string | null>(null);

  async function loadSettings(): Promise<void> {
    settingsLoading = true;
    try {
      settings = (await getLlmProviderSettings()) as LlmSettings;
    } catch (e) {
      notifyError(e instanceof Error ? e.message : String(e));
    } finally {
      settingsLoading = false;
    }
  }

  async function saveProviders(): Promise<void> {
    if (!settings) return;
    await updateLlmProviderSettings(settings as unknown as LlmProviderSettingsDocument);
    queryClient.setQueryData(queryKeys.llmProviders, settings.providers);
    notifySuccess("Providers saved");
  }

  async function onTestConnection(provider: LlmSettings["providers"][number]): Promise<void> {
    const res = await testLlmProviderConnection({
      provider_id: String(provider.id || ""),
      settings: provider.settings || {},
    });
    if (!res?.ok) throw new Error(res?.detail || "Connection test failed");
    const fetchedModels = Array.isArray(res?.models) ? res.models : [];
    if (!settings) return;
    const next = structuredClone(settings);
    const idx = next.providers.findIndex((x) => x?.id === provider?.id);
    if (idx >= 0) {
      const p = next.providers[idx] as Record<string, unknown>;
      p.models = fetchedModels;
      p.models_verified = true;
    }
    settings = next;
    notifySuccess("Connection OK — models updated");
  }

  async function loadAgent(aid: string): Promise<void> {
    agentLoading = true;
    agentLoadError = null;
    currentAgent = null;
    try {
      currentAgent = await getAgentById(aid);
    } catch (e) {
      agentLoadError = e instanceof Error ? e.message : String(e);
    } finally {
      agentLoading = false;
    }
  }

  async function saveAgent(): Promise<boolean> {
    if (!currentAgent) throw new Error("No agent loaded");
    const saved = await updateAgentById(currentAgent.id, {
      name: currentAgent.name,
      system_prompt: currentAgent.system_prompt,
      default_llm_configuration: currentAgent.default_llm_configuration,
      default_model_preset_id: currentAgent.default_model_preset_id,
      icon: currentAgent.icon,
      color: currentAgent.color,
    });
    currentAgent = saved;
    await queryClient.invalidateQueries({ queryKey: queryKeys.agents });
    notifySuccess("Agent saved");
    return true;
  }

  async function saveAgentAndOpenChat(targetId?: string): Promise<boolean> {
    if (!currentAgent) throw new Error("No agent loaded");
    await saveAgent();
    const id = targetId || currentAgent.id;
    navigate(`/chat/new?agent=${encodeURIComponent(id)}`);
    return true;
  }

  async function createAgent(): Promise<void> {
    const created = await createAgentApi();
    await queryClient.invalidateQueries({ queryKey: queryKeys.agents });
    onAgentEditIdChange(created.id);
    await loadAgent(created.id);
    notifySuccess("Agent created");
  }

  async function setLoadedAgentAsDefault(): Promise<void> {
    if (!currentAgent) return;
    const updated = await setDefaultAgent(currentAgent.id);
    currentAgent = updated;
    await queryClient.invalidateQueries({ queryKey: queryKeys.agents });
  }

  async function deleteLoadedAgent(): Promise<void> {
    if (!currentAgent) return;
    await deleteAgentById(currentAgent.id);
    await queryClient.invalidateQueries({ queryKey: queryKeys.agents });
    const remaining = agentsQuery.data ?? [];
    if (remaining.length > 0) {
      onAgentEditIdChange(remaining[0].id);
      await loadAgent(remaining[0].id);
    } else {
      onAgentEditIdChange("");
      currentAgent = null;
    }
    notifySuccess("Agent deleted");
  }

  async function loadToolCatalog(): Promise<void> {
    try {
      const rows = await getTools();
      toolCatalog = Array.isArray(rows)
        ? rows.filter((x) => x && typeof x === "object" && !Array.isArray(x)) as Record<string, unknown>[]
        : [];
    } catch {
      toolCatalog = [];
    }
  }

  async function loadPreset(id: number): Promise<void> {
    presetLoading = true;
    presetLoadError = null;
    currentPreset = null;
    try {
      currentPreset = await getModelPresetById(id);
    } catch (e) {
      presetLoadError = e instanceof Error ? e.message : String(e);
    } finally {
      presetLoading = false;
    }
  }

  async function savePreset(): Promise<boolean> {
    if (!currentPreset) throw new Error("No preset loaded");
    const saved = await updateModelPresetById(currentPreset.id, {
      name: currentPreset.name,
      parameters: currentPreset.parameters,
    });
    currentPreset = saved;
    await queryClient.invalidateQueries({ queryKey: queryKeys.modelPresets });
    notifySuccess("Preset saved");
    return true;
  }

  async function createPreset(): Promise<void> {
    const created = await createModelPreset({});
    await queryClient.invalidateQueries({ queryKey: queryKeys.modelPresets });
    onPresetEditIdChange(created.id);
    await loadPreset(created.id);
    notifySuccess("Model preset created");
  }

  async function deleteLoadedPreset(): Promise<void> {
    if (!currentPreset) return;
    await deleteModelPresetById(currentPreset.id);
    await queryClient.invalidateQueries({ queryKey: queryKeys.modelPresets });
    const remaining = presetsQuery.data ?? [];
    if (remaining.length > 0) {
      onPresetEditIdChange(remaining[0].id);
      await loadPreset(remaining[0].id);
    } else {
      onPresetEditIdChange(null);
      currentPreset = null;
    }
    notifySuccess("Model preset deleted");
  }

  function goSection(section: SettingsSection): void {
    navigate(`/settings/${section}${$chatSearch}`);
  }

  function onAgentEditIdChange(id: string): void {
    agentEditId = id;
    const params = new URLSearchParams($chatSearch);
    if (id.trim()) params.set("agent", id.trim());
    else params.delete("agent");
    const q = params.toString();
    navigate(`/settings/agents${q ? `?${q}` : ""}`);
  }

  function onPresetEditIdChange(id: number | null): void {
    presetEditId = id;
    const params = new URLSearchParams($chatSearch);
    if (id != null) params.set("preset", String(id));
    else params.delete("preset");
    const q = params.toString();
    navigate(`/settings/model-presets${q ? `?${q}` : ""}`);
  }

  $effect(() => {
    void loadSettings();
  });

  $effect(() => {
    const fromUrl = new URLSearchParams($chatSearch).get("agent")?.trim() || "";
    if (fromUrl) agentEditId = fromUrl;
    const rawPreset = new URLSearchParams($chatSearch).get("preset")?.trim() || "";
    presetEditId = /^\d+$/.test(rawPreset) ? Number(rawPreset) : null;
  });

  $effect(() => {
    if (activeSection !== "agents") return;
    const agents = agentsQuery.data ?? [];
    void loadToolCatalog().then(() => {
      if (agents.length === 0) return;
      if (agentEditId && agents.some((a) => a.id === agentEditId)) return;
      onAgentEditIdChange(agents[0].id);
    });
  });

  $effect(() => {
    if (activeSection === "agents" && agentEditId) void loadAgent(agentEditId);
  });

  $effect(() => {
    if (activeSection !== "model-presets") return;
    const presets = presetsQuery.data ?? [];
    if (presets.length === 0) return;
    if (presetEditId != null && presets.some((p) => p.id === presetEditId)) return;
    onPresetEditIdChange(presets[0].id);
  });

  $effect(() => {
    if (activeSection === "model-presets" && presetEditId != null) void loadPreset(presetEditId);
  });
</script>

<section class="min-h-0 w-full flex-1 overflow-auto">
  <div class="grid grid-cols-1 gap-4 p-4 md:grid-cols-[280px_minmax(0,1fr)]">
    <SettingsSidebar {activeSection} settingsSearch={$chatSearch} onNavigate={goSection} />
    <SettingsSectionView
      section={activeSection}
      {settings}
      {settingsLoading}
      {providerSearch}
      {modelFilters}
      {collapsedModels}
      onSettingsChange={(next) => (settings = next)}
      onProviderSearchChange={(value) => (providerSearch = value)}
      onModelFilterChange={(providerId, value) => (modelFilters = { ...modelFilters, [providerId]: value })}
      onCollapsedModelsChange={(providerId, collapsed) =>
        (collapsedModels = { ...collapsedModels, [providerId]: collapsed })}
      onSaveProviders={saveProviders}
      onTestConnection={onTestConnection}
      agents={agentsQuery.data ?? []}
      {agentEditId}
      onAgentEditIdChange={onAgentEditIdChange}
      {currentAgent}
      onCurrentAgentChange={(agent) => (currentAgent = agent)}
      {agentLoadError}
      {agentLoading}
      {toolCatalog}
      onSaveAgent={saveAgent}
      onSaveAgentAndOpenChat={saveAgentAndOpenChat}
      onCreateAgent={createAgent}
      onDeleteAgent={deleteLoadedAgent}
      onSetDefaultAgent={setLoadedAgentAsDefault}
      presets={presetsQuery.data ?? []}
      {presetEditId}
      onPresetEditIdChange={onPresetEditIdChange}
      {currentPreset}
      onCurrentPresetChange={(preset) => (currentPreset = preset)}
      {presetLoadError}
      {presetLoading}
      onSavePreset={savePreset}
      onCreatePreset={createPreset}
      onDeletePreset={deleteLoadedPreset}
    />
  </div>
</section>
