// frontend/src/components/ui/CopyButton.tsx
import { useEffect, useRef, useState } from "react";
import { Check, Copy } from "lucide-react";
import { cn } from "@/lib/utils";
import { notifyError } from "@/utils/toast";

type CopyButtonProps = {
  value: string;
  className?: string;
  title?: string;
};

export function CopyButton({ value, className, title = "Copy" }: CopyButtonProps) {
  const [copied, setCopied] = useState(false);
  const timerRef = useRef<number | null>(null);

  useEffect(
    () => () => {
      if (timerRef.current !== null) window.clearTimeout(timerRef.current);
    },
    [],
  );

  async function onCopy() {
    if (!value) return;
    try {
      await navigator.clipboard.writeText(value);
    } catch (e) {
      const detail = e instanceof Error ? e.message : String(e);
      notifyError(`Copy failed: ${detail}`);
      return;
    }
    setCopied(true);
    if (timerRef.current !== null) window.clearTimeout(timerRef.current);
    timerRef.current = window.setTimeout(() => setCopied(false), 1500);
  }

  return (
    <button
      type="button"
      onClick={() => {
        void onCopy();
      }}
      title={copied ? "Copied" : title}
      aria-label={copied ? "Copied" : title}
      className={cn(
        "inline-flex h-5 w-5 items-center justify-center rounded text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground",
        className,
      )}
    >
      {copied ? <Check className="h-3 w-3 text-primary" /> : <Copy className="h-3 w-3" />}
    </button>
  );
}

// frontend/src/components/ui/CopyButton.svelte
<script lang="ts">
  import { notifyError } from "@/utils/toast";

  let {
    value,
    title = "Copy",
    class: className = "",
  }: {
    value: string;
    title?: string;
    class?: string;
  } = $props();

  let copied = $state(false);
  let timer: ReturnType<typeof setTimeout> | null = null;

  async function onCopy(): Promise<void> {
    if (!value) return;
    try {
      await navigator.clipboard.writeText(value);
    } catch (e) {
      notifyError(`Copy failed: ${e instanceof Error ? e.message : String(e)}`);
      return;
    }
    copied = true;
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => {
      copied = false;
    }, 1500);
  }
</script>

<button
  type="button"
  onclick={() => void onCopy()}
  title={copied ? "Copied" : title}
  aria-label={copied ? "Copied" : title}
  class="inline-flex h-5 w-5 items-center justify-center rounded text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground {className}"
>
  {#if copied}
    <svg class="h-3 w-3 text-primary" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
      <path d="M20 6 9 17l-5-5" />
    </svg>
  {:else}
    <svg class="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
      <rect width="14" height="14" x="8" y="8" rx="2" ry="2" />
      <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
    </svg>
  {/if}
</button>
