// frontend/src/components/ui/ModelDropdown.tsx
import type { ReactNode } from "react";
import { useEffect, useMemo, useRef, useState } from "react";
import { ChevronDown } from "lucide-react";
import type { DropdownItem, ModelGroup } from "../../pages/settings/helpers";
import { TextInput } from "./TextInput";
import { cn } from "@/lib/utils";
import { Popover, PopoverContent, PopoverTrigger } from "./popover";

function normalizeToken(value: unknown): string {
  return String(value || "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
}

function itemValue(item: DropdownItem): string {
  return typeof item === "string" ? item : item.value;
}

function itemLabel(item: DropdownItem): string {
  return typeof item === "string" ? item : item.label;
}

function itemClassName(item: DropdownItem): string | undefined {
  return typeof item === "string" ? undefined : item.className;
}

type ModelDropdownProps = {
  value: string;
  onChange: (value: string, groupId?: string) => void;
  groups: ModelGroup[];
  placeholder?: string;
  searchPlaceholder?: string;
  footer?: ReactNode;
  disabled?: boolean;
  buttonClassName?: string;
  initialOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
};

export function ModelDropdown({
  value,
  onChange,
  groups,
  placeholder = "Select model",
  searchPlaceholder = "Search model",
  footer,
  disabled = false,
  buttonClassName,
  initialOpen = false,
  onOpenChange,
}: ModelDropdownProps) {
  const [open, setOpen] = useState(initialOpen);
  const [query, setQuery] = useState("");
  const searchInputRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    if (disabled) setOpen(false);
  }, [disabled]);

  useEffect(() => {
    onOpenChange?.(open);
  }, [open, onOpenChange]);

  useEffect(() => {
    if (!open) return;
    const id = requestAnimationFrame(() => searchInputRef.current?.focus());
    return () => cancelAnimationFrame(id);
  }, [open]);

  const normalizedQuery = normalizeToken(query);

  const filteredGroups = useMemo(() => {
    const qRaw = query.trim().toLowerCase();
    if (!qRaw) return groups;
    return groups
      .map((g) => {
        const models = (g.models || []).filter((m) => {
          const raw = itemLabel(m).toLowerCase();
          return raw.includes(qRaw) || normalizeToken(raw).includes(normalizedQuery);
        });
        return { ...g, models };
      })
      .filter((g) => g.models.length > 0);
  }, [groups, query, normalizedQuery]);

  const selectedLabel = useMemo(() => {
    for (const g of groups) {
      for (const m of g.models || []) {
        if (itemValue(m) === value) return itemLabel(m);
      }
    }
    return value || "";
  }, [groups, value]);

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <button
          type="button"
          className={cn(
            "flex min-h-[28px] w-full cursor-pointer items-center justify-between gap-2 rounded-md border border-input bg-muted/40 px-2.5 py-1 text-left text-sm text-foreground",
            disabled && "cursor-not-allowed opacity-55",
            buttonClassName,
          )}
          disabled={disabled}
        >
          <span className={cn("min-w-0 flex-1 truncate whitespace-nowrap", !selectedLabel && "text-muted-foreground")}>
            {selectedLabel || placeholder}
          </span>
          <span
            className={cn(
              "inline-flex h-4 w-4 shrink-0 items-center justify-center text-muted-foreground transition-transform duration-150",
              open && "rotate-180",
            )}
            aria-hidden
          >
            <ChevronDown className="h-3.5 w-3.5" strokeWidth={2} />
          </span>
        </button>
      </PopoverTrigger>
      <PopoverContent
        align="center"
        sideOffset={6}
        className="z-[1400] w-fit max-w-[90vw] overflow-hidden rounded-lg border border-border bg-popover p-0 shadow-xl"
      >
        <div className="border-b border-border p-2.5">
          <TextInput
            inputRef={searchInputRef}
            value={query}
            onChange={setQuery}
            placeholder={searchPlaceholder}
            className="box-border w-full rounded-md border border-input bg-muted/40 py-1.5 pl-2 pr-8 text-sm"
            showClearButton
            wrapperClassName="relative block"
            clearButtonClassName="absolute right-1.5 top-1/2 flex h-[18px] w-[18px] -translate-y-1/2 items-center justify-center rounded-full border border-border bg-background p-0 leading-none text-muted-foreground"
            clearAriaLabel="Clear search"
          />
        </div>

        <div className="max-h-[300px] overflow-auto px-2 pb-2 pt-1.5">
          {filteredGroups.length === 0 ? (
            <div className="px-1.5 py-2 text-[13px] text-muted-foreground">No results</div>
          ) : null}
          {filteredGroups.map((g) => (
            <div key={g.id} className="mt-1.5 first:mt-0">
              {g.label ? <div className="px-1.5 py-1 text-xs font-bold text-muted-foreground">{g.label}</div> : null}
              {g.models.map((m) => {
                const v = itemValue(m);
                const l = itemLabel(m);
                const extraClass = itemClassName(m);
                return (
                  <button
                    key={`${g.id}:${v}`}
                    type="button"
                    className={cn(
                      "block cursor-pointer whitespace-nowrap rounded-md border-0 bg-transparent px-2.5 py-2 text-left font-mono text-sm text-foreground hover:bg-primary/10",
                      v === value && "bg-primary/15",
                      extraClass,
                    )}
                    onClick={() => {
                      onChange(v, g.id);
                      setOpen(false);
                    }}
                  >
                    {l}
                  </button>
                );
              })}
            </div>
          ))}
        </div>

        {footer ? (
          <div className="border-t border-border px-3 py-2 text-[13px] [&_a]:cursor-pointer [&_a]:font-semibold [&_a]:text-primary [&_a]:no-underline hover:[&_a]:underline [&_button]:cursor-pointer [&_button]:border-0 [&_button]:bg-transparent [&_button]:p-0 [&_button]:font-semibold [&_button]:text-primary">
            {footer}
          </div>
        ) : null}
      </PopoverContent>
    </Popover>
  );
}

// frontend/src/components/ui/ModelDropdown.svelte
<script lang="ts">
  import { popupPosition } from "@/lib/popupPosition";
  import { portal } from "@/lib/portal";
  import type { DropdownItem, ModelGroup } from "@/pages/settings/helpers";
  import type { Snippet } from "svelte";

  function normalizeToken(value: unknown): string {
    return String(value || "")
      .toLowerCase()
      .replace(/[^a-z0-9]/g, "");
  }

  function itemValue(item: DropdownItem): string {
    return typeof item === "string" ? item : item.value;
  }

  function itemLabel(item: DropdownItem): string {
    return typeof item === "string" ? item : item.label;
  }

  function itemClassName(item: DropdownItem): string | undefined {
    return typeof item === "string" ? undefined : item.className;
  }

  let {
    value,
    onChange,
    groups,
    placeholder = "Select model",
    searchPlaceholder = "Search model",
    header,
    footer,
    disabled = false,
    buttonClass = "",
    initialOpen = false,
    onOpenChange,
  }: {
    value: string;
    onChange: (value: string, groupId?: string) => void;
    groups: ModelGroup[];
    placeholder?: string;
    searchPlaceholder?: string;
    /** Rendered at the top of the (portaled) panel, above the search input. */
    header?: Snippet;
    footer?: Snippet;
    disabled?: boolean;
    buttonClass?: string;
    initialOpen?: boolean;
    onOpenChange?: (open: boolean) => void;
  } = $props();

  // Capturing only the prop's initial value is the intent (it seeds local state).
  // svelte-ignore state_referenced_locally
  let open = $state(initialOpen);
  let query = $state("");
  let searchInput = $state<HTMLInputElement | null>(null);
  let anchor = $state<HTMLButtonElement | null>(null);
  let panel = $state<HTMLDivElement | null>(null);

  $effect(() => {
    if (disabled) open = false;
  });

  $effect(() => {
    onOpenChange?.(open);
  });

  $effect(() => {
    if (!open) {
      query = "";
      return;
    }
    const id = requestAnimationFrame(() => searchInput?.focus());

    function onDocMouseDown(event: MouseEvent): void {
      const target = event.target;
      if (!(target instanceof Node)) return;
      if (anchor?.contains(target) || panel?.contains(target)) return;
      open = false;
    }

    document.addEventListener("mousedown", onDocMouseDown);
    return () => {
      cancelAnimationFrame(id);
      document.removeEventListener("mousedown", onDocMouseDown);
    };
  });

  const normalizedQuery = $derived(normalizeToken(query));

  const filteredGroups = $derived.by(() => {
    const qRaw = query.trim().toLowerCase();
    if (!qRaw) return groups;
    return groups
      .map((g) => ({
        ...g,
        models: (g.models || []).filter((m) => {
          const raw = itemLabel(m).toLowerCase();
          return raw.includes(qRaw) || normalizeToken(raw).includes(normalizedQuery);
        }),
      }))
      .filter((g) => g.models.length > 0);
  });

  const selectedLabel = $derived.by(() => {
    for (const g of groups) {
      for (const m of g.models || []) {
        if (itemValue(m) === value) return itemLabel(m);
      }
    }
    return value || "";
  });
</script>

<div class="relative">
  <button
    bind:this={anchor}
    type="button"
    class="flex min-h-[28px] w-full cursor-pointer items-center justify-between gap-2 rounded-md border border-input bg-muted/40 px-2.5 py-1 text-left text-sm text-foreground {disabled
      ? 'cursor-not-allowed opacity-55'
      : ''} {buttonClass}"
    {disabled}
    onclick={() => {
      open = !open;
    }}
  >
    <span class="min-w-0 flex-1 truncate whitespace-nowrap {!selectedLabel ? 'text-muted-foreground' : ''}">
      {selectedLabel || placeholder}
    </span>
    <span class="inline-flex h-4 w-4 shrink-0 items-center justify-center text-muted-foreground transition-transform duration-150 {open ? 'rotate-180' : ''}" aria-hidden="true">
      <svg class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="m6 9 6 6 6-6" />
      </svg>
    </span>
  </button>
</div>

{#if open}
  <div
    use:portal
    use:popupPosition={{ anchor, minWidthFromAnchor: true }}
    bind:this={panel}
    class="fixed z-[1500] flex w-fit max-w-[min(90vw,calc(100vw-1rem))] flex-col overflow-hidden rounded-lg border border-border bg-popover shadow-xl"
    role="listbox"
  >
    {#if header}
      <div class="shrink-0 border-b border-border p-2.5">
        {@render header()}
      </div>
    {/if}
    <div class="shrink-0 border-b border-border p-2.5">
      <input
        bind:this={searchInput}
        class="box-border w-full rounded-md border border-input bg-muted/40 py-1.5 pl-2 pr-8 text-sm"
        placeholder={searchPlaceholder}
        bind:value={query}
      />
    </div>
    <div class="min-h-0 flex-1 overflow-auto px-2 pb-2 pt-1.5">
      {#if filteredGroups.length === 0}
        <div class="px-1.5 py-2 text-[13px] text-muted-foreground">No results</div>
      {/if}
      {#each filteredGroups as g (g.id)}
        <div class="mt-1.5 first:mt-0">
          {#if g.label}
            <div class="px-1.5 py-1 text-xs font-bold text-muted-foreground">{g.label}</div>
          {/if}
          {#each g.models as m (`${g.id}:${itemValue(m)}`)}
            {@const v = itemValue(m)}
            {@const l = itemLabel(m)}
            {@const extra = itemClassName(m)}
            <button
              type="button"
              class="block w-full cursor-pointer whitespace-nowrap rounded-md border-0 bg-transparent px-2.5 py-2 text-left font-mono text-sm text-foreground hover:bg-primary/10 {v === value ? 'bg-primary/15' : ''} {extra ?? ''}"
              onclick={() => {
                onChange(v, g.id);
                open = false;
              }}
            >
              {l}
            </button>
          {/each}
        </div>
      {/each}
    </div>
    {#if footer}
      <div class="shrink-0 border-t border-border px-3 py-2 text-[13px] [&_a]:font-semibold [&_a]:text-primary [&_a]:no-underline hover:[&_a]:underline">
        {@render footer()}
      </div>
    {/if}
  </div>
{/if}
