// frontend/src/components/ui/Spinner.tsx
import { cn } from "@/lib/utils";

type SpinnerProps = {
  size?: number;
  className?: string;
};

export function Spinner({ size = 14, className }: SpinnerProps) {
  return (
    <span
      className={cn(
        "inline-block shrink-0 rounded-full border-2 border-muted border-t-foreground/60 align-middle animate-spin",
        className,
      )}
      style={{ width: `${size}px`, height: `${size}px` }}
      aria-hidden="true"
    />
  );
}

// frontend/src/components/ui/Spinner.svelte
<script lang="ts">
  let { size = 20, class: className = "" }: { size?: number; class?: string } = $props();
</script>

<span
  class="inline-block animate-spin rounded-full border-2 border-muted-foreground/30 border-t-muted-foreground {className}"
  style="width: {size}px; height: {size}px;"
  role="status"
  aria-label="Loading"
></span>
