// frontend/src/components/chat/rows/AssistantMessageRow.svelte
<script lang="ts">
  import type { AssistantMessageEntry } from "@/protocol/chatEntry";
  import CopyButton from "@/components/ui/CopyButton.svelte";
  import MarkdownContent from "@/components/ui/MarkdownContent.svelte";
  import { formatExactChatTime, formatRelativeChatTime } from "@/utils/formatRelativeChatTime";
  import BranchSelector from "../BranchSelector.svelte";
  import ChatMessageShell from "../ChatMessageShell.svelte";
  import FoldFromHereButton from "./FoldFromHereButton.svelte";

  let {
    entry,
    conversationId,
  }: {
    entry: AssistantMessageEntry;
    conversationId: string;
  } = $props();

  const relativeTime = $derived(formatRelativeChatTime(entry.createdAt));
  const exactTime = $derived(formatExactChatTime(entry.createdAt));
</script>

<ChatMessageShell role="agent">
  {#snippet badge()}
    <div class="flex items-center gap-1">
      {#if relativeTime}
        <span
          class="text-[11px] font-normal normal-case tracking-normal text-muted-foreground"
          title={exactTime || undefined}
        >
          {relativeTime}
        </span>
      {/if}
      <BranchSelector entryId={entry.id} />
      <FoldFromHereButton {conversationId} entryId={entry.id} />
      {#if entry.text}
        <CopyButton value={entry.text} title="Copy message" />
      {/if}
    </div>
  {/snippet}
  {#snippet children()}
    {#if entry.text}
      <MarkdownContent content={entry.text} />
    {/if}
  {/snippet}
</ChatMessageShell>

// frontend/src/components/chat/rows/AssistantMessageRow.tsx
import type { AssistantMessageEntry } from "../../../protocol/chatEntry";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { CopyButton } from "@/components/ui/CopyButton";
import { formatExactChatTime, formatRelativeChatTime } from "../../../utils/formatRelativeChatTime";
import { ChatMessageShell } from "../ChatMessageShell";
import { BranchSelector } from "../BranchSelector";
import { FoldFromHereButton } from "./FoldFromHereButton";

/* frontend2 body uses text-sm leading-relaxed; prose for markdown (slightly roomier than ultra-compact thread) */
const proseChat =
  "prose prose-sm max-w-none leading-relaxed text-foreground dark:prose-invert prose-p:my-2 prose-p:first:mt-0 prose-p:last:mb-0 prose-headings:my-2 prose-headings:scroll-mt-4 prose-headings:first:mt-0 prose-pre:my-2 prose-pre:rounded-md prose-pre:bg-zinc-950 prose-pre:p-2 prose-pre:text-[13px] prose-pre:leading-snug prose-pre:text-zinc-100 prose-code:rounded prose-code:bg-muted prose-code:px-1 prose-code:py-px prose-code:text-[0.875em] prose-code:before:content-none prose-code:after:content-none prose-pre:prose-code:bg-transparent prose-pre:prose-code:p-0 prose-ul:my-2 prose-ol:my-2 prose-li:my-0.5 prose-table:my-2 prose-th:border prose-th:border-border prose-th:px-2 prose-th:py-1.5 prose-th:text-left prose-td:border prose-td:border-border prose-td:px-2 prose-td:py-1.5";

export function AssistantMessageRow({
  entry,
  conversationId,
}: {
  entry: AssistantMessageEntry;
  conversationId: string;
}) {
  const relativeTime = formatRelativeChatTime(entry.createdAt);
  const exactTime = formatExactChatTime(entry.createdAt);
  return (
    <ChatMessageShell
      role="agent"
      badge={
        <div className="flex items-center gap-1">
          {relativeTime ? (
            <span
              className="text-[11px] font-normal normal-case tracking-normal text-muted-foreground"
              title={exactTime || undefined}
            >
              {relativeTime}
            </span>
          ) : null}
          <BranchSelector entryId={entry.id} />
          <FoldFromHereButton conversationId={conversationId} entryId={entry.id} />
          {entry.text ? <CopyButton value={entry.text} title="Copy message" /> : null}
        </div>
      }
    >
      {entry.text ? (
        <div className={proseChat}>
          <ReactMarkdown
            remarkPlugins={[remarkGfm]}
            components={{
              a: ({ node: _node, ...props }) => <a {...props} target="_blank" rel="noreferrer noopener" />,
            }}
          >
            {entry.text}
          </ReactMarkdown>
        </div>
      ) : null}
    </ChatMessageShell>
  );
}
