// frontend/src/components/chat/rows/ThoughtTripletRow.svelte
<script lang="ts">
  import { isThoughtStreamEntry, type ChatEntry, type ThoughtPrepareEntry } from "@/protocol/chatEntry";
  import type { ObservableItem } from "@/utils/observableCollection";
  import Icon from "@/components/ui/Icon.svelte";
  import TokenTooltip from "@/components/ui/TokenTooltip.svelte";
  import { createAgentsQuery, createModelCapabilitiesQuery, pricingFromCapabilities } from "@/hooks/queries/referenceData";
  import { getChatSessionContext, type ThoughtStage } from "@/lib/chatSessionContext";
  import { resolveStreamTokenBreakdown, streamTotalTokens } from "@/lib/providerCost";
  import { formatTokenCount } from "@/utils/formatTokenCount";
  import BranchSelector from "../BranchSelector.svelte";
  import ChatThreadIndent from "../ChatThreadIndent.svelte";
  import RowIcon from "../RowIcon.svelte";
  import StepChip from "./StepChip.svelte";
  import ThoughtTripletExpanded from "./ThoughtTripletExpanded.svelte";
  import { actionMetaLabel, displayStatus, findAncestorUserMessage, isAgentDefaultLlm } from "./thoughtTriplet/meta";
  import TryModelBranchButton from "./thoughtTriplet/TryModelBranchButton.svelte";

  let {
    prepareEntry,
    conversationId,
    streamEntry$,
    actionEntry = null,
  }: {
    prepareEntry: ChatEntry;
    conversationId: string;
    streamEntry$?: ObservableItem<ChatEntry>;
    actionEntry?: ChatEntry | null;
  } = $props();

  const capabilitiesQuery = createModelCapabilitiesQuery();
  const agentsQuery = createAgentsQuery();
  const session = getChatSessionContext();
  let expanded = $state<ThoughtStage | null>(null);
  const pricingByModel = $derived(pricingFromCapabilities(capabilitiesQuery.data));

  const activeEntriesById = $derived.by(() => {
    const map = new Map<string, ChatEntry>();
    for (const row$ of session.getActivePathEntries()) {
      const entry = row$.get();
      map.set(entry.id, entry);
    }
    return map;
  });

  const thoughtAgent = $derived.by(() => {
    if (prepareEntry.type !== "thought-prepare") return null;
    const userMsg = findAncestorUserMessage(prepareEntry.parentId, activeEntriesById);
    if (!userMsg) return null;
    return (agentsQuery.data ?? []).find((agent) => agent.id === userMsg.agentId) ?? null;
  });

  let streamRaw = $state<ChatEntry | null>(null);

  const stream = $derived.by(() => {
    const raw = streamRaw;
    return raw && isThoughtStreamEntry(raw) ? raw : null;
  });

  $effect(() => {
    const row$ = streamEntry$;
    if (!row$) {
      streamRaw = null;
      return;
    }
    streamRaw = row$.get();
    return row$.subscribe(() => {
      streamRaw = row$.get();
    });
  });

  function toggle(stage: ThoughtStage): void {
    expanded = expanded === stage ? null : stage;
  }

  $effect(() => {
    void conversationId;
    expanded = null;
  });

  function reasonMetaParts(streamEntry: NonNullable<typeof stream>) {
    const provider = String(streamEntry.llm?.providerId || "").trim() || "unknown-provider";
    const model = String(streamEntry.llm?.model || "").trim() || "unknown-model";
    const status = displayStatus(streamEntry.status ?? "running");
    const tokens = resolveStreamTokenBreakdown(streamEntry);
    const totalTokens = streamTotalTokens(streamEntry);
    const durationLabel = streamEntry.thoughtMs != null ? `${Math.round(streamEntry.thoughtMs)}ms` : "";
    const pricing = pricingByModel.get(model);
    const showModel = !isAgentDefaultLlm(streamEntry.llm, thoughtAgent);
    const providerCost =
      typeof streamEntry.provider_cost === "number" && Number.isFinite(streamEntry.provider_cost)
        ? streamEntry.provider_cost
        : null;
    return {
      provider,
      model,
      status,
      promptTokens: tokens.input,
      cachedTokens: tokens.cached,
      completionTokens: tokens.output,
      totalTokens,
      durationLabel,
      pricing,
      showModel,
      providerCost,
    };
  }
</script>

{#if prepareEntry.type !== "thought-prepare"}
  <!-- invalid -->
{:else if streamEntry$ && stream}
  {@const prep = prepareEntry as ThoughtPrepareEntry}
  {@const actionStep = actionEntry?.type === "thought-action" ? actionEntry : null}
  {@const contextTitle = String(prep.title ?? "").trim() || "Preparation"}
  {@const actionMeta = actionMetaLabel(actionStep, stream)}
  {@const actionLabel = actionMeta.usesTool ? `call ${actionMeta.toolName ?? "tool"}` : "Reply"}
  {@const reasonFailed = stream.status === "failed" || stream.status === "cancelled"}
  {@const reasonMeta = reasonMetaParts(stream)}
  <ChatThreadIndent class="py-0 mb-1">
    {#snippet children()}
      <div class="my-0 border-l-2 border-border/60 pl-3">
        <div class="flex items-stretch gap-2 py-0.5 text-[11px] text-muted-foreground">
          <StepChip testId="thought-step-context" label={contextTitle} active={expanded === "context"} onclick={() => toggle("context")}>
            {#snippet icon()}<RowIcon name="file" />{/snippet}
            {#snippet badge()}
              <span class="inline-flex items-center gap-0.5">
                <TryModelBranchButton prepareEntry={prep} {stream} {conversationId} />
                <BranchSelector entryId={prep.id} />
              </span>
            {/snippet}
          </StepChip>
          <Icon name="arrow-right" class="h-3 w-3 self-center opacity-60" />
          <StepChip testId="thought-step-reasoning" label="" active={expanded === "reasoning"} onclick={() => toggle("reasoning")}>
            {#snippet badge()}<BranchSelector entryId={stream.id} />{/snippet}
            {#snippet icon()}
              {#if reasonFailed}
                <RowIcon name="alert" />
              {:else if stream.status === "running"}
                <span class="h-3 w-3 animate-spin rounded-full border border-current border-t-transparent" aria-hidden="true"></span>
              {:else}
                <RowIcon name="sparkles" />
              {/if}
            {/snippet}
            {#snippet metaSlot()}
              {#if reasonMeta.totalTokens > 0}
                <TokenTooltip
                  promptTokens={reasonMeta.promptTokens}
                  cachedTokens={reasonMeta.cachedTokens}
                  completionTokens={reasonMeta.completionTokens}
                  pricing={reasonMeta.pricing}
                  providerCost={reasonMeta.providerCost}
                >
                  {#snippet children()}{formatTokenCount(reasonMeta.totalTokens)}{/snippet}
                </TokenTooltip>
              {/if}
              {#if reasonMeta.durationLabel}<span>{reasonMeta.durationLabel}</span>{/if}
              {#if reasonMeta.showModel || expanded === "reasoning"}<span>{reasonMeta.provider}/{reasonMeta.model}</span>{/if}
              {#if reasonMeta.status}<span>{reasonMeta.status}</span>{/if}
            {/snippet}
          </StepChip>
          <Icon name="arrow-right" class="h-3 w-3 self-center opacity-60" />
          <StepChip
            label={actionLabel}
            meta={actionMeta.status}
            align="right"
            active={expanded === "action"}
            testId="thought-step-action"
            onclick={() => toggle("action")}
          >
            {#snippet icon()}
              <RowIcon name={actionMeta.usesTool ? "wrench" : "message"} />
            {/snippet}
            {#snippet badge()}
              {#if actionStep}<BranchSelector entryId={actionStep.id} />{/if}
            {/snippet}
          </StepChip>
        </div>
        {#if expanded === "context"}
          <ThoughtTripletExpanded stage="context" prepareEntry={prep} {stream} actionEntry={actionStep} {conversationId} />
        {:else if expanded === "reasoning"}
          <ThoughtTripletExpanded stage="reasoning" prepareEntry={prep} {stream} actionEntry={actionStep} {conversationId} />
        {:else if expanded === "action"}
          <ThoughtTripletExpanded stage="action" prepareEntry={prep} {stream} actionEntry={actionStep} {conversationId} />
        {/if}
      </div>
    {/snippet}
  </ChatThreadIndent>
{:else if prepareEntry.type === "thought-prepare"}
  {@const prep = prepareEntry as ThoughtPrepareEntry}
  {@const contextTitle = String(prep.title ?? "").trim() || "Preparation"}
  <ChatThreadIndent class="py-0 mb-1">
    {#snippet children()}
      <div class="my-0 border-l-2 border-border/60 pl-3">
        <div class="flex items-stretch gap-2 py-0.5 text-[11px] text-muted-foreground">
          <StepChip label={contextTitle} active={false} onclick={() => undefined}>
            {#snippet icon()}<RowIcon name="file" />{/snippet}
          </StepChip>
          <Icon name="arrow-right" class="h-3 w-3 self-center opacity-60" />
          <StepChip label="" meta="reasoning…" active={false} onclick={() => undefined}>
            {#snippet icon()}
              <span class="h-3 w-3 animate-spin rounded-full border border-current border-t-transparent" aria-hidden="true"></span>
            {/snippet}
          </StepChip>
        </div>
      </div>
    {/snippet}
  </ChatThreadIndent>
{/if}

// frontend/src/components/chat/rows/ThoughtTripletRow.tsx
import type { ReactNode } from "react";
import { AlertTriangle, FileText, MessageSquare, Sparkles, Wrench } from "lucide-react";
import { isThoughtStreamEntry, type ChatEntry, type ThoughtPrepareEntry, type ThoughtStreamEntry } from "@/protocol/chatEntry";
import type { ObservableItem } from "@/utils/observableCollection";
import { useObservableValue } from "@/hooks/useObservable";
import { useChatSessionContext, type ThoughtStage } from "@/hooks/chatSessionContext";
import { usePricingMap } from "@/hooks/usePricingMap";
import { BranchSelector } from "../BranchSelector";
import { ChatThreadIndent } from "../ChatMessageShell";
import { ActionStep } from "./thoughtTriplet/ActionStep";
import { ContextStep } from "./thoughtTriplet/ContextStep";
import { ReasoningStep } from "./thoughtTriplet/ReasoningStep";
import { actionMetaLabel, displayStatus } from "./thoughtTriplet/meta";
import { TryModelBranchButton } from "./thoughtTriplet/TryModelBranchButton";
import { Connector, StepChip, TinyProgressCircle } from "./thoughtTriplet/StepChip";
import { TokenTooltip } from "@/components/ui/TokenTooltip";
import { formatTokenCount } from "@/utils/formatTokenCount";
import type { ModelPricing } from "@/lib/costEstimation";

type ThoughtTripletRowProps = {
  prepareEntry: ChatEntry;
  conversationId: string;
  streamEntry$?: ObservableItem<ChatEntry>;
  actionEntry?: ChatEntry | null;
};

export function ThoughtTripletRow({ prepareEntry, streamEntry$, conversationId, actionEntry }: ThoughtTripletRowProps) {
  if (prepareEntry.type !== "thought-prepare") return null;
  if (streamEntry$) {
    return (
      <ThoughtTripletRowWithStream
        prepareEntry={prepareEntry}
        streamEntry$={streamEntry$}
        conversationId={conversationId}
        actionEntry={actionEntry ?? null}
      />
    );
  }
  return <ThoughtTripletRowPrepareOnly prepareEntry={prepareEntry} />;
}

function ThoughtTripletRowWithStream({
  prepareEntry,
  streamEntry$,
  conversationId,
  actionEntry,
}: {
  prepareEntry: ThoughtPrepareEntry;
  streamEntry$: ObservableItem<ChatEntry>;
  conversationId: string;
  actionEntry: ChatEntry | null;
}) {
  const stream = useObservableValue(streamEntry$);
  const { expandedStageBySlotKey, setSlotExpandedStage } = useChatSessionContext();
  const pricingByModel = usePricingMap();

  if (!isThoughtStreamEntry(stream)) return <ThoughtTripletRowPrepareOnly prepareEntry={prepareEntry} />;
  const actionStepEntry = actionEntry?.type === "thought-action" ? actionEntry : null;
  const slotKey = prepareEntry.parentId ?? stream.thoughtId;
  const expanded = expandedStageBySlotKey.get(slotKey) ?? null;
  const toggle = (stage: ThoughtStage) => setSlotExpandedStage(slotKey, expanded === stage ? null : stage);
  const contextTitle = String(prepareEntry.title ?? "").trim() || "Preparation";
  const modelLabel = String(stream.llm?.model || "").trim();
  const reasonMeta = buildReasonMetaNode(stream, pricingByModel.get(modelLabel));
  const actionMeta = actionMetaLabel(actionStepEntry, stream);
  const actionLabel = actionMeta.usesTool ? `call ${actionMeta.toolName ?? "tool"}` : "Reply";
  const reasonFailed = stream.status === "failed" || stream.status === "cancelled";
  const reasonIcon = reasonFailed ? (
    <AlertTriangle className="h-3 w-3 text-destructive" />
  ) : stream.status === "running" ? (
    <TinyProgressCircle />
  ) : (
    <Sparkles className="h-3 w-3" />
  );

  return (
    <ChatThreadIndent className="py-0 mb-1">
      <div className="my-0 border-l-2 border-border/60 pl-3">
        <div className="flex items-stretch gap-2 py-0.5 text-[11px] text-muted-foreground">
          <StepChip
            icon={<FileText className="h-3 w-3" />}
            label={contextTitle}
            badge={
              <span className="inline-flex items-center gap-0.5">
                <TryModelBranchButton prepareEntry={prepareEntry} stream={stream} conversationId={conversationId} />
                <BranchSelector entryId={prepareEntry.id} />
              </span>
            }
            active={expanded === "context"}
            onClick={() => toggle("context")}
          />
          <Connector />
          <StepChip
            icon={reasonIcon}
            label=""
            meta={reasonMeta}
            badge={<BranchSelector entryId={stream.id} />}
            active={expanded === "reasoning"}
            onClick={() => toggle("reasoning")}
          />
          <Connector />
          <StepChip
            icon={actionMeta.usesTool ? <Wrench className="h-3 w-3" /> : <MessageSquare className="h-3 w-3" />}
            label={actionLabel}
            meta={actionMeta.status}
            badge={actionStepEntry ? <BranchSelector entryId={actionStepEntry.id} /> : null}
            active={expanded === "action"}
            align="right"
            onClick={() => toggle("action")}
          />
        </div>

        {expanded === "context" ? <ContextStep prepareEntry={prepareEntry} stream={stream} conversationId={conversationId} /> : null}
        {expanded === "reasoning" ? <ReasoningStep stream={stream} prepareEntry={prepareEntry} conversationId={conversationId} /> : null}
        {expanded === "action" ? <ActionStep actionEntry={actionStepEntry} stream={stream} /> : null}
      </div>
    </ChatThreadIndent>
  );
}

function buildReasonMetaNode(stream: ThoughtStreamEntry, pricing: ModelPricing | undefined): ReactNode {
  const provider = String(stream.llm?.providerId || "").trim() || "unknown-provider";
  const model = String(stream.llm?.model || "").trim() || "unknown-model";
  const status = displayStatus(stream.status ?? "running");
  const promptTokens = stream.promptTokens ?? 0;
  const cachedTokens = stream.cachedPromptTokens ?? 0;
  const completionTokens = stream.completionTokens ?? 0;
  const totalTokens = promptTokens + cachedTokens + completionTokens;
  const durationLabel = stream.thoughtMs != null ? `${Math.round(stream.thoughtMs)}ms` : "";

  const parts: ReactNode[] = [];
  if (totalTokens > 0) {
    parts.push(
      <TokenTooltip key="tok" promptTokens={promptTokens} cachedTokens={cachedTokens} completionTokens={completionTokens} pricing={pricing}>
        {formatTokenCount(totalTokens)}
      </TokenTooltip>,
    );
  }
  if (durationLabel) parts.push(durationLabel);
  parts.push(`${provider}/${model}`);
  if (status) parts.push(status);

  return (
    <>
      {parts.map((part, i) => (
        // biome-ignore lint/suspicious/noArrayIndexKey: stable order
        <span key={i}>{i > 0 ? " · " : ""}{part}</span>
      ))}
    </>
  );
}

function ThoughtTripletRowPrepareOnly({ prepareEntry }: { prepareEntry: ThoughtPrepareEntry }) {
  const contextTitle = String(prepareEntry.title ?? "").trim() || "Preparation";
  const noop = () => undefined;
  return (
    <ChatThreadIndent className="py-0 mb-1">
      <div className="my-0 border-l-2 border-border/60 pl-3">
        <div className="flex items-stretch gap-2 py-0.5 text-[11px] text-muted-foreground">
          <StepChip
            icon={<FileText className="h-3 w-3" />}
            label={contextTitle}
            badge={<BranchSelector entryId={prepareEntry.id} />}
            active={false}
            onClick={noop}
          />
          <Connector />
          <StepChip icon={<TinyProgressCircle />} label="" meta="reasoning…" active={false} onClick={noop} />
        </div>
      </div>
    </ChatThreadIndent>
  );
}
