// frontend/src/components/conversationSidebar/NewGroupDialog.tsx
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

type NewGroupDialogProps = {
  conversationId: string;
  open: boolean;
  newGroupName: string;
  onOpenChange: (open: boolean) => void;
  onNewGroupNameChange: (value: string) => void;
  onSubmit: () => void | Promise<void>;
};

export function NewGroupDialog({
  conversationId,
  open,
  newGroupName,
  onOpenChange,
  onNewGroupNameChange,
  onSubmit,
}: NewGroupDialogProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>New group</DialogTitle>
          <DialogDescription>Move this conversation to a new group.</DialogDescription>
        </DialogHeader>
        <div className="space-y-1.5">
          <label className="text-xs font-medium text-muted-foreground" htmlFor={`new-group-${conversationId}`}>
            Group name
          </label>
          <input
            id={`new-group-${conversationId}`}
            className="box-border min-h-[34px] w-full rounded-md border border-input bg-background px-3 text-sm"
            value={newGroupName}
            onChange={(e) => onNewGroupNameChange(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                e.preventDefault();
                void onSubmit();
              }
            }}
            placeholder="e.g. Work"
            autoFocus
          />
        </div>
        <DialogFooter>
          <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button type="button" onClick={() => void onSubmit()}>
            Create group
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// frontend3/src/components/sidebar/NewGroupDialog.svelte
<script lang="ts">
  let {
    open,
    newGroupName,
    onOpenChange,
    onNewGroupNameChange,
    onSubmit,
  }: {
    open: boolean;
    newGroupName: string;
    onOpenChange: (open: boolean) => void;
    onNewGroupNameChange: (name: string) => void;
    onSubmit: () => void | Promise<void>;
  } = $props();
</script>

{#if open}
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
    <div class="w-full max-w-sm rounded-lg border border-border bg-card p-4 shadow-lg">
      <h2 class="mb-3 text-sm font-medium">New group</h2>
      <input
        class="mb-3 w-full rounded-md border border-input bg-background px-2 py-1.5 text-sm"
        placeholder="Group name"
        value={newGroupName}
        oninput={(e) => onNewGroupNameChange(e.currentTarget.value)}
        onkeydown={(e) => {
          if (e.key === "Enter") void onSubmit();
          if (e.key === "Escape") onOpenChange(false);
        }}
      />
      <div class="flex justify-end gap-2">
        <button type="button" class="rounded-md px-2 py-1 text-xs text-muted-foreground" onclick={() => onOpenChange(false)}>
          Cancel
        </button>
        <button
          type="button"
          class="rounded-md bg-primary px-2 py-1 text-xs text-primary-foreground"
          onclick={() => void onSubmit()}
        >
          Create
        </button>
      </div>
    </div>
  </div>
{/if}
